/* AUTO-GENERATED by GraphQL Code Generator — DO NOT EDIT. Plan 152. */
// @ts-nocheck

/** Internal type. DO NOT USE DIRECTLY. */
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] }
/** Internal type. DO NOT USE DIRECTLY. */
export type Incremental<T> =
  | T
  | { [P in keyof T]?: P extends " $fragmentName" | "__typename" ? T[P] : never }
import type * as Types from "../../../platform/graphql/generated/schema-types.generated"

import * as z from "zod"
import type {
  TraceSort,
  TestResultStatus,
  TestFlakyState,
  TestExplorerSort,
  TestRollup,
  TestConfigurationFilterInput,
  TestIdentitySource,
  SignalKind,
  IssueSort,
  AttributeFilterInput,
  AlertRuleInput,
  TestCaseDetailQuery,
} from "@/platform/graphql/generated/schema-types.generated"
import type { TypedDocumentNode as DocumentNode } from "@/platform/graphql/typed-document"
export type TestFlakyState = "BROKEN" | "FIXED" | "FLAKY" | "HEALTHY"

export type TestIdentitySource = "CODE_REFERENCE" | "EXPLICIT" | "NAME_PATH"

export type TestResultStatus = "BROKEN" | "FAILED" | "PASSED" | "SKIPPED" | "UNKNOWN"

export type TestCaseDetailQueryVariables = Exact<{
  caseKey: string
  variantLimit?: number | null | undefined
  resultLimit?: number | null | undefined
}>

export type TestCaseDetailQuery = {
  readonly testCase: {
    readonly caseKey: string
    readonly name: string
    readonly identitySource: Types.TestIdentitySource
    readonly suitePath: ReadonlyArray<string>
    readonly codeReference: string | null
    readonly explicitId: string | null
    readonly firstSeenNanos: string
    readonly lastSeenNanos: string
    readonly variants: ReadonlyArray<{
      readonly variantKey: string
      readonly firstSeenNanos: string
      readonly lastSeenNanos: string
      readonly parameters: ReadonlyArray<{
        readonly name: string
        readonly value: string
        readonly excluded: boolean
      }>
      readonly history: ReadonlyArray<{
        readonly invocationId: string
        readonly attempt: number
        readonly status: Types.TestResultStatus
        readonly traceId: string
        readonly spanId: string
        readonly startedAtNanos: string
        readonly endedAtNanos: string
        readonly service: string
        readonly serviceVersion: string | null
        readonly vcsHeadRevision: string | null
        readonly failureFingerprint: string | null
        readonly configuration: ReadonlyArray<{ readonly key: string; readonly value: string }>
      }>
      readonly flaky: {
        readonly state: Types.TestFlakyState
        readonly sameCommitDivergence: boolean
        readonly intraInvocationMix: boolean
        readonly transitionCount: number
        readonly consecutivePasses: number
        readonly updatedAtNanos: string
      } | null
    }>
  } | null
}

export const TestCaseDetailDocument = {
  kind: "Document",
  definitions: [
    {
      kind: "OperationDefinition",
      operation: "query",
      name: { kind: "Name", value: "TestCaseDetail" },
      variableDefinitions: [
        {
          kind: "VariableDefinition",
          variable: { kind: "Variable", name: { kind: "Name", value: "caseKey" } },
          type: {
            kind: "NonNullType",
            type: { kind: "NamedType", name: { kind: "Name", value: "String" } },
          },
        },
        {
          kind: "VariableDefinition",
          variable: { kind: "Variable", name: { kind: "Name", value: "variantLimit" } },
          type: { kind: "NamedType", name: { kind: "Name", value: "Int" } },
        },
        {
          kind: "VariableDefinition",
          variable: { kind: "Variable", name: { kind: "Name", value: "resultLimit" } },
          type: { kind: "NamedType", name: { kind: "Name", value: "Int" } },
        },
      ],
      selectionSet: {
        kind: "SelectionSet",
        selections: [
          {
            kind: "Field",
            name: { kind: "Name", value: "testCase" },
            arguments: [
              {
                kind: "Argument",
                name: { kind: "Name", value: "caseKey" },
                value: { kind: "Variable", name: { kind: "Name", value: "caseKey" } },
              },
              {
                kind: "Argument",
                name: { kind: "Name", value: "variantLimit" },
                value: { kind: "Variable", name: { kind: "Name", value: "variantLimit" } },
              },
              {
                kind: "Argument",
                name: { kind: "Name", value: "resultLimit" },
                value: { kind: "Variable", name: { kind: "Name", value: "resultLimit" } },
              },
            ],
            selectionSet: {
              kind: "SelectionSet",
              selections: [
                { kind: "Field", name: { kind: "Name", value: "caseKey" } },
                { kind: "Field", name: { kind: "Name", value: "name" } },
                { kind: "Field", name: { kind: "Name", value: "identitySource" } },
                { kind: "Field", name: { kind: "Name", value: "suitePath" } },
                { kind: "Field", name: { kind: "Name", value: "codeReference" } },
                { kind: "Field", name: { kind: "Name", value: "explicitId" } },
                { kind: "Field", name: { kind: "Name", value: "firstSeenNanos" } },
                { kind: "Field", name: { kind: "Name", value: "lastSeenNanos" } },
                {
                  kind: "Field",
                  name: { kind: "Name", value: "variants" },
                  selectionSet: {
                    kind: "SelectionSet",
                    selections: [
                      { kind: "Field", name: { kind: "Name", value: "variantKey" } },
                      {
                        kind: "Field",
                        name: { kind: "Name", value: "parameters" },
                        selectionSet: {
                          kind: "SelectionSet",
                          selections: [
                            { kind: "Field", name: { kind: "Name", value: "name" } },
                            { kind: "Field", name: { kind: "Name", value: "value" } },
                            { kind: "Field", name: { kind: "Name", value: "excluded" } },
                          ],
                        },
                      },
                      { kind: "Field", name: { kind: "Name", value: "firstSeenNanos" } },
                      { kind: "Field", name: { kind: "Name", value: "lastSeenNanos" } },
                      {
                        kind: "Field",
                        name: { kind: "Name", value: "history" },
                        selectionSet: {
                          kind: "SelectionSet",
                          selections: [
                            { kind: "Field", name: { kind: "Name", value: "invocationId" } },
                            { kind: "Field", name: { kind: "Name", value: "attempt" } },
                            { kind: "Field", name: { kind: "Name", value: "status" } },
                            { kind: "Field", name: { kind: "Name", value: "traceId" } },
                            { kind: "Field", name: { kind: "Name", value: "spanId" } },
                            { kind: "Field", name: { kind: "Name", value: "startedAtNanos" } },
                            { kind: "Field", name: { kind: "Name", value: "endedAtNanos" } },
                            { kind: "Field", name: { kind: "Name", value: "service" } },
                            { kind: "Field", name: { kind: "Name", value: "serviceVersion" } },
                            { kind: "Field", name: { kind: "Name", value: "vcsHeadRevision" } },
                            { kind: "Field", name: { kind: "Name", value: "failureFingerprint" } },
                            {
                              kind: "Field",
                              name: { kind: "Name", value: "configuration" },
                              selectionSet: {
                                kind: "SelectionSet",
                                selections: [
                                  { kind: "Field", name: { kind: "Name", value: "key" } },
                                  { kind: "Field", name: { kind: "Name", value: "value" } },
                                ],
                              },
                            },
                          ],
                        },
                      },
                      {
                        kind: "Field",
                        name: { kind: "Name", value: "flaky" },
                        selectionSet: {
                          kind: "SelectionSet",
                          selections: [
                            { kind: "Field", name: { kind: "Name", value: "state" } },
                            {
                              kind: "Field",
                              name: { kind: "Name", value: "sameCommitDivergence" },
                            },
                            { kind: "Field", name: { kind: "Name", value: "intraInvocationMix" } },
                            { kind: "Field", name: { kind: "Name", value: "transitionCount" } },
                            { kind: "Field", name: { kind: "Name", value: "consecutivePasses" } },
                            { kind: "Field", name: { kind: "Name", value: "updatedAtNanos" } },
                          ],
                        },
                      },
                    ],
                  },
                },
              ],
            },
          },
        ],
      },
    },
  ],
} as unknown as DocumentNode<TestCaseDetailQuery, TestCaseDetailQueryVariables>

type Properties<T> = {
  [K in keyof T]: z.ZodType<T[K], T[K] | undefined>
}

type definedNonNullAny = {}

export const isDefinedNonNullAny = (v: any): v is definedNonNullAny => v !== undefined && v !== null

export const definedNonNullAnySchema = z.any().refine((v) => isDefinedNonNullAny(v))

export const TraceSortSchema: z.ZodType<
  "DURATION_ASC" | "DURATION_DESC" | "SPAN_COUNT_DESC" | "START_DESC",
  "DURATION_ASC" | "DURATION_DESC" | "SPAN_COUNT_DESC" | "START_DESC"
> = z.enum(["DURATION_ASC", "DURATION_DESC", "SPAN_COUNT_DESC", "START_DESC"])

export const TestResultStatusSchema: z.ZodType<
  "BROKEN" | "FAILED" | "PASSED" | "SKIPPED" | "UNKNOWN",
  "BROKEN" | "FAILED" | "PASSED" | "SKIPPED" | "UNKNOWN"
> = z.enum(["BROKEN", "FAILED", "PASSED", "SKIPPED", "UNKNOWN"])

export const TestFlakyStateSchema: z.ZodType<
  "BROKEN" | "FIXED" | "FLAKY" | "HEALTHY",
  "BROKEN" | "FIXED" | "FLAKY" | "HEALTHY"
> = z.enum(["BROKEN", "FIXED", "FLAKY", "HEALTHY"])

export const TestExplorerSortSchema: z.ZodType<"LAST_SEEN" | "NAME", "LAST_SEEN" | "NAME"> = z.enum(
  ["LAST_SEEN", "NAME"]
)

export const TestRollupSchema: z.ZodType<
  "BROKEN" | "FAILED" | "FLAKY_PASS" | "PASSED" | "SKIPPED" | "UNKNOWN",
  "BROKEN" | "FAILED" | "FLAKY_PASS" | "PASSED" | "SKIPPED" | "UNKNOWN"
> = z.enum(["BROKEN", "FAILED", "FLAKY_PASS", "PASSED", "SKIPPED", "UNKNOWN"])

export const TestIdentitySourceSchema: z.ZodType<
  "CODE_REFERENCE" | "EXPLICIT" | "NAME_PATH",
  "CODE_REFERENCE" | "EXPLICIT" | "NAME_PATH"
> = z.enum(["CODE_REFERENCE", "EXPLICIT", "NAME_PATH"])

export const SignalKindSchema: z.ZodType<
  "ERRORS" | "LOGS" | "METRIC_POINTS" | "SPANS" | "TRACES",
  "ERRORS" | "LOGS" | "METRIC_POINTS" | "SPANS" | "TRACES"
> = z.enum(["ERRORS", "LOGS", "METRIC_POINTS", "SPANS", "TRACES"])

export const IssueSortSchema: z.ZodType<
  "EVENTS" | "FIRST_SEEN" | "LAST_SEEN" | "TREND",
  "EVENTS" | "FIRST_SEEN" | "LAST_SEEN" | "TREND"
> = z.enum(["EVENTS", "FIRST_SEEN", "LAST_SEEN", "TREND"])

export const TestConfigurationFilterInputSchema: z.ZodObject<
  Properties<TestConfigurationFilterInput>
> = z.object({
  key: z.string(),
  value: z.string(),
})

export const AttributeFilterInputSchema: z.ZodObject<Properties<AttributeFilterInput>> = z.object({
  key: z.string(),
  op: z.string(),
  value: z.string(),
})

export const AlertRuleInputSchema: z.ZodObject<Properties<AlertRuleInput>> = z.object({
  attributeFilters: z.string().nullable(),
  comparator: z.string(),
  consecutiveBreachesRequired: z.number().nullable(),
  consecutiveHealthyRequired: z.number().nullable(),
  destinationIds: z.array(z.string()).nullable(),
  enabled: z.boolean().nullable(),
  excludeServices: z.array(z.string()).nullable(),
  groupBy: z.string().nullable(),
  id: z.string().nullable(),
  metricAggregation: z.string().nullable(),
  metricName: z.string().nullable(),
  minimumSampleCount: z.number().nullable(),
  name: z.string(),
  noDataBehavior: z.string().nullable(),
  renotifyIntervalMinutes: z.number().nullable(),
  services: z.array(z.string()).nullable(),
  severity: z.string(),
  signalType: z.string(),
  threshold: z.number(),
  thresholdUpper: z.number().nullable(),
  windowMinutes: z.number(),
})

export const TestCaseDetailQuerySchema: z.ZodType<TestCaseDetailQuery> = z.object({
  testCase: z
    .object({
      caseKey: z.string(),
      name: z.string(),
      identitySource: TestIdentitySourceSchema,
      suitePath: z.array(z.string()),
      codeReference: z.string().nullable(),
      explicitId: z.string().nullable(),
      firstSeenNanos: z.string(),
      lastSeenNanos: z.string(),
      variants: z.array(
        z.object({
          variantKey: z.string(),
          parameters: z.array(
            z.object({
              name: z.string(),
              value: z.string(),
              excluded: z.boolean(),
            })
          ),
          firstSeenNanos: z.string(),
          lastSeenNanos: z.string(),
          history: z.array(
            z.object({
              invocationId: z.string(),
              attempt: z.number(),
              status: TestResultStatusSchema,
              traceId: z.string(),
              spanId: z.string(),
              startedAtNanos: z.string(),
              endedAtNanos: z.string(),
              service: z.string(),
              serviceVersion: z.string().nullable(),
              vcsHeadRevision: z.string().nullable(),
              failureFingerprint: z.string().nullable(),
              configuration: z.array(
                z.object({
                  key: z.string(),
                  value: z.string(),
                })
              ),
            })
          ),
          flaky: z
            .object({
              state: TestFlakyStateSchema,
              sameCommitDivergence: z.boolean(),
              intraInvocationMix: z.boolean(),
              transitionCount: z.number(),
              consecutivePasses: z.number(),
              updatedAtNanos: z.string(),
            })
            .nullable(),
        })
      ),
    })
    .nullable(),
})
