/* AUTO-GENERATED by GraphQL Code Generator — DO NOT EDIT. Plan 152. */
// @ts-nocheck

/** Internal type. DO NOT USE DIRECTLY. */
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] }
/** Internal type. DO NOT USE DIRECTLY. */
export type Incremental<T> =
  | T
  | { [P in keyof T]?: P extends " $fragmentName" | "__typename" ? T[P] : never }
import type * as Types from "../../../platform/graphql/generated/schema-types.generated"

import * as z from "zod"
import type {
  TraceSort,
  TestResultStatus,
  TestFlakyState,
  TestExplorerSort,
  TestRollup,
  TestConfigurationFilterInput,
  TestIdentitySource,
  SignalKind,
  IssueSort,
  AttributeFilterInput,
  AlertRuleInput,
  PipelineStatusQuery,
} from "@/platform/graphql/generated/schema-types.generated"
import type { TypedDocumentNode as DocumentNode } from "@/platform/graphql/typed-document"
export type PipelineStatusQueryVariables = Exact<{ [key: string]: never }>

export type PipelineStatusQuery = {
  readonly samplingPolicy: ReadonlyArray<{
    readonly signal: string
    readonly service: string | null
    readonly rule: string
    readonly rate: number
    readonly enforcedBy: string
    readonly description: string
  }>
  readonly ingestDrops: ReadonlyArray<{
    readonly signal: string | null
    readonly reason: string
    readonly count: string
    readonly detail: string
  }>
  readonly ingestQueues: ReadonlyArray<{
    readonly signal: string
    readonly depth: number
    readonly capacity: number
    readonly highWater: number
    readonly accepted: string
  }>
}

export const PipelineStatusDocument = {
  kind: "Document",
  definitions: [
    {
      kind: "OperationDefinition",
      operation: "query",
      name: { kind: "Name", value: "PipelineStatus" },
      selectionSet: {
        kind: "SelectionSet",
        selections: [
          {
            kind: "Field",
            name: { kind: "Name", value: "samplingPolicy" },
            selectionSet: {
              kind: "SelectionSet",
              selections: [
                { kind: "Field", name: { kind: "Name", value: "signal" } },
                { kind: "Field", name: { kind: "Name", value: "service" } },
                { kind: "Field", name: { kind: "Name", value: "rule" } },
                { kind: "Field", name: { kind: "Name", value: "rate" } },
                { kind: "Field", name: { kind: "Name", value: "enforcedBy" } },
                { kind: "Field", name: { kind: "Name", value: "description" } },
              ],
            },
          },
          {
            kind: "Field",
            name: { kind: "Name", value: "ingestDrops" },
            selectionSet: {
              kind: "SelectionSet",
              selections: [
                { kind: "Field", name: { kind: "Name", value: "signal" } },
                { kind: "Field", name: { kind: "Name", value: "reason" } },
                { kind: "Field", name: { kind: "Name", value: "count" } },
                { kind: "Field", name: { kind: "Name", value: "detail" } },
              ],
            },
          },
          {
            kind: "Field",
            name: { kind: "Name", value: "ingestQueues" },
            selectionSet: {
              kind: "SelectionSet",
              selections: [
                { kind: "Field", name: { kind: "Name", value: "signal" } },
                { kind: "Field", name: { kind: "Name", value: "depth" } },
                { kind: "Field", name: { kind: "Name", value: "capacity" } },
                { kind: "Field", name: { kind: "Name", value: "highWater" } },
                { kind: "Field", name: { kind: "Name", value: "accepted" } },
              ],
            },
          },
        ],
      },
    },
  ],
} as unknown as DocumentNode<PipelineStatusQuery, PipelineStatusQueryVariables>

type Properties<T> = {
  [K in keyof T]: z.ZodType<T[K], T[K] | undefined>
}

type definedNonNullAny = {}

export const isDefinedNonNullAny = (v: any): v is definedNonNullAny => v !== undefined && v !== null

export const definedNonNullAnySchema = z.any().refine((v) => isDefinedNonNullAny(v))

export const TraceSortSchema: z.ZodType<
  "DURATION_ASC" | "DURATION_DESC" | "SPAN_COUNT_DESC" | "START_DESC",
  "DURATION_ASC" | "DURATION_DESC" | "SPAN_COUNT_DESC" | "START_DESC"
> = z.enum(["DURATION_ASC", "DURATION_DESC", "SPAN_COUNT_DESC", "START_DESC"])

export const TestResultStatusSchema: z.ZodType<
  "BROKEN" | "FAILED" | "PASSED" | "SKIPPED" | "UNKNOWN",
  "BROKEN" | "FAILED" | "PASSED" | "SKIPPED" | "UNKNOWN"
> = z.enum(["BROKEN", "FAILED", "PASSED", "SKIPPED", "UNKNOWN"])

export const TestFlakyStateSchema: z.ZodType<
  "BROKEN" | "FIXED" | "FLAKY" | "HEALTHY",
  "BROKEN" | "FIXED" | "FLAKY" | "HEALTHY"
> = z.enum(["BROKEN", "FIXED", "FLAKY", "HEALTHY"])

export const TestExplorerSortSchema: z.ZodType<"LAST_SEEN" | "NAME", "LAST_SEEN" | "NAME"> = z.enum(
  ["LAST_SEEN", "NAME"]
)

export const TestRollupSchema: z.ZodType<
  "BROKEN" | "FAILED" | "FLAKY_PASS" | "PASSED" | "SKIPPED" | "UNKNOWN",
  "BROKEN" | "FAILED" | "FLAKY_PASS" | "PASSED" | "SKIPPED" | "UNKNOWN"
> = z.enum(["BROKEN", "FAILED", "FLAKY_PASS", "PASSED", "SKIPPED", "UNKNOWN"])

export const TestIdentitySourceSchema: z.ZodType<
  "CODE_REFERENCE" | "EXPLICIT" | "NAME_PATH",
  "CODE_REFERENCE" | "EXPLICIT" | "NAME_PATH"
> = z.enum(["CODE_REFERENCE", "EXPLICIT", "NAME_PATH"])

export const SignalKindSchema: z.ZodType<
  "ERRORS" | "LOGS" | "METRIC_POINTS" | "SPANS" | "TRACES",
  "ERRORS" | "LOGS" | "METRIC_POINTS" | "SPANS" | "TRACES"
> = z.enum(["ERRORS", "LOGS", "METRIC_POINTS", "SPANS", "TRACES"])

export const IssueSortSchema: z.ZodType<
  "EVENTS" | "FIRST_SEEN" | "LAST_SEEN" | "TREND",
  "EVENTS" | "FIRST_SEEN" | "LAST_SEEN" | "TREND"
> = z.enum(["EVENTS", "FIRST_SEEN", "LAST_SEEN", "TREND"])

export const TestConfigurationFilterInputSchema: z.ZodObject<
  Properties<TestConfigurationFilterInput>
> = z.object({
  key: z.string(),
  value: z.string(),
})

export const AttributeFilterInputSchema: z.ZodObject<Properties<AttributeFilterInput>> = z.object({
  key: z.string(),
  op: z.string(),
  value: z.string(),
})

export const AlertRuleInputSchema: z.ZodObject<Properties<AlertRuleInput>> = z.object({
  attributeFilters: z.string().nullable(),
  comparator: z.string(),
  consecutiveBreachesRequired: z.number().nullable(),
  consecutiveHealthyRequired: z.number().nullable(),
  destinationIds: z.array(z.string()).nullable(),
  enabled: z.boolean().nullable(),
  excludeServices: z.array(z.string()).nullable(),
  groupBy: z.string().nullable(),
  id: z.string().nullable(),
  metricAggregation: z.string().nullable(),
  metricName: z.string().nullable(),
  minimumSampleCount: z.number().nullable(),
  name: z.string(),
  noDataBehavior: z.string().nullable(),
  renotifyIntervalMinutes: z.number().nullable(),
  services: z.array(z.string()).nullable(),
  severity: z.string(),
  signalType: z.string(),
  threshold: z.number(),
  thresholdUpper: z.number().nullable(),
  windowMinutes: z.number(),
})

export const PipelineStatusQuerySchema: z.ZodType<PipelineStatusQuery> = z.object({
  samplingPolicy: z.array(
    z.object({
      signal: z.string(),
      service: z.string().nullable(),
      rule: z.string(),
      rate: z.number(),
      enforcedBy: z.string(),
      description: z.string(),
    })
  ),
  ingestDrops: z.array(
    z.object({
      signal: z.string().nullable(),
      reason: z.string(),
      count: z.string(),
      detail: z.string(),
    })
  ),
  ingestQueues: z.array(
    z.object({
      signal: z.string(),
      depth: z.number(),
      capacity: z.number(),
      highWater: z.number(),
      accepted: z.string(),
    })
  ),
})
