msrv = "1.97.0"
too-many-lines-threshold = 100
cognitive-complexity-threshold = 25
too-many-arguments-threshold = 6
excessive-nesting-threshold = 4
allow-expect-in-tests = true
allow-indexing-slicing-in-tests = true
allow-panic-in-tests = true
allow-unwrap-in-tests = true
