/* AUTO-GENERATED by GraphQL Code Generator — DO NOT EDIT. Plan 152. */
// @ts-nocheck

/** Internal type. DO NOT USE DIRECTLY. */
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] }
/** Internal type. DO NOT USE DIRECTLY. */
export type Incremental<T> =
  | T
  | {
      [P in keyof T]?: P extends " $fragmentName" | "__typename" ? T[P] : never
    }
import type * as Types from "../../../platform/graphql/generated/schema-types.generated"

import * as z from "zod"
import type {
  TraceSort,
  SignalKind,
  IssueSort,
  AttributeFilterInput,
  AlertRuleInput,
  RuntimeMetricStripQuery,
} from "@/platform/graphql/generated/schema-types.generated"
import type { TypedDocumentNode as DocumentNode } from "@/platform/graphql/typed-document"
export type RuntimeMetricStripQueryVariables = Exact<{
  fromNanos: string
  toNanos: string
  stepSeconds: number
  service?: string | null | undefined
  invocationId?: string | null | undefined
}>

export type RuntimeMetricStripQuery = {
  readonly cpu: ReadonlyArray<{
    readonly points: ReadonlyArray<{
      readonly tsNanos: string
      readonly value: number
    }>
  }>
  readonly memory: ReadonlyArray<{
    readonly points: ReadonlyArray<{
      readonly tsNanos: string
      readonly value: number
    }>
  }>
  readonly tasks: ReadonlyArray<{
    readonly points: ReadonlyArray<{
      readonly tsNanos: string
      readonly value: number
    }>
  }>
}

export const RuntimeMetricStripDocument = {
  kind: "Document",
  definitions: [
    {
      kind: "OperationDefinition",
      operation: "query",
      name: { kind: "Name", value: "RuntimeMetricStrip" },
      variableDefinitions: [
        {
          kind: "VariableDefinition",
          variable: {
            kind: "Variable",
            name: { kind: "Name", value: "fromNanos" },
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: { kind: "Name", value: "String" },
            },
          },
        },
        {
          kind: "VariableDefinition",
          variable: {
            kind: "Variable",
            name: { kind: "Name", value: "toNanos" },
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: { kind: "Name", value: "String" },
            },
          },
        },
        {
          kind: "VariableDefinition",
          variable: {
            kind: "Variable",
            name: { kind: "Name", value: "stepSeconds" },
          },
          type: {
            kind: "NonNullType",
            type: { kind: "NamedType", name: { kind: "Name", value: "Int" } },
          },
        },
        {
          kind: "VariableDefinition",
          variable: {
            kind: "Variable",
            name: { kind: "Name", value: "service" },
          },
          type: { kind: "NamedType", name: { kind: "Name", value: "String" } },
        },
        {
          kind: "VariableDefinition",
          variable: {
            kind: "Variable",
            name: { kind: "Name", value: "invocationId" },
          },
          type: { kind: "NamedType", name: { kind: "Name", value: "String" } },
        },
      ],
      selectionSet: {
        kind: "SelectionSet",
        selections: [
          {
            kind: "Field",
            alias: { kind: "Name", value: "cpu" },
            name: { kind: "Name", value: "metricSeries" },
            arguments: [
              {
                kind: "Argument",
                name: { kind: "Name", value: "name" },
                value: {
                  kind: "StringValue",
                  value: "process.cpu.utilization",
                  block: false,
                },
              },
              {
                kind: "Argument",
                name: { kind: "Name", value: "fromNanos" },
                value: {
                  kind: "Variable",
                  name: { kind: "Name", value: "fromNanos" },
                },
              },
              {
                kind: "Argument",
                name: { kind: "Name", value: "toNanos" },
                value: {
                  kind: "Variable",
                  name: { kind: "Name", value: "toNanos" },
                },
              },
              {
                kind: "Argument",
                name: { kind: "Name", value: "stepSeconds" },
                value: {
                  kind: "Variable",
                  name: { kind: "Name", value: "stepSeconds" },
                },
              },
              {
                kind: "Argument",
                name: { kind: "Name", value: "service" },
                value: {
                  kind: "Variable",
                  name: { kind: "Name", value: "service" },
                },
              },
              {
                kind: "Argument",
                name: { kind: "Name", value: "invocationId" },
                value: {
                  kind: "Variable",
                  name: { kind: "Name", value: "invocationId" },
                },
              },
            ],
            selectionSet: {
              kind: "SelectionSet",
              selections: [
                {
                  kind: "Field",
                  name: { kind: "Name", value: "points" },
                  selectionSet: {
                    kind: "SelectionSet",
                    selections: [
                      {
                        kind: "Field",
                        name: { kind: "Name", value: "tsNanos" },
                      },
                      { kind: "Field", name: { kind: "Name", value: "value" } },
                    ],
                  },
                },
              ],
            },
          },
          {
            kind: "Field",
            alias: { kind: "Name", value: "memory" },
            name: { kind: "Name", value: "metricSeries" },
            arguments: [
              {
                kind: "Argument",
                name: { kind: "Name", value: "name" },
                value: {
                  kind: "StringValue",
                  value: "process.memory.usage",
                  block: false,
                },
              },
              {
                kind: "Argument",
                name: { kind: "Name", value: "fromNanos" },
                value: {
                  kind: "Variable",
                  name: { kind: "Name", value: "fromNanos" },
                },
              },
              {
                kind: "Argument",
                name: { kind: "Name", value: "toNanos" },
                value: {
                  kind: "Variable",
                  name: { kind: "Name", value: "toNanos" },
                },
              },
              {
                kind: "Argument",
                name: { kind: "Name", value: "stepSeconds" },
                value: {
                  kind: "Variable",
                  name: { kind: "Name", value: "stepSeconds" },
                },
              },
              {
                kind: "Argument",
                name: { kind: "Name", value: "service" },
                value: {
                  kind: "Variable",
                  name: { kind: "Name", value: "service" },
                },
              },
              {
                kind: "Argument",
                name: { kind: "Name", value: "invocationId" },
                value: {
                  kind: "Variable",
                  name: { kind: "Name", value: "invocationId" },
                },
              },
            ],
            selectionSet: {
              kind: "SelectionSet",
              selections: [
                {
                  kind: "Field",
                  name: { kind: "Name", value: "points" },
                  selectionSet: {
                    kind: "SelectionSet",
                    selections: [
                      {
                        kind: "Field",
                        name: { kind: "Name", value: "tsNanos" },
                      },
                      { kind: "Field", name: { kind: "Name", value: "value" } },
                    ],
                  },
                },
              ],
            },
          },
          {
            kind: "Field",
            alias: { kind: "Name", value: "tasks" },
            name: { kind: "Name", value: "metricSeries" },
            arguments: [
              {
                kind: "Argument",
                name: { kind: "Name", value: "name" },
                value: {
                  kind: "StringValue",
                  value: "tokio.runtime.alive_tasks",
                  block: false,
                },
              },
              {
                kind: "Argument",
                name: { kind: "Name", value: "fromNanos" },
                value: {
                  kind: "Variable",
                  name: { kind: "Name", value: "fromNanos" },
                },
              },
              {
                kind: "Argument",
                name: { kind: "Name", value: "toNanos" },
                value: {
                  kind: "Variable",
                  name: { kind: "Name", value: "toNanos" },
                },
              },
              {
                kind: "Argument",
                name: { kind: "Name", value: "stepSeconds" },
                value: {
                  kind: "Variable",
                  name: { kind: "Name", value: "stepSeconds" },
                },
              },
              {
                kind: "Argument",
                name: { kind: "Name", value: "service" },
                value: {
                  kind: "Variable",
                  name: { kind: "Name", value: "service" },
                },
              },
              {
                kind: "Argument",
                name: { kind: "Name", value: "invocationId" },
                value: {
                  kind: "Variable",
                  name: { kind: "Name", value: "invocationId" },
                },
              },
            ],
            selectionSet: {
              kind: "SelectionSet",
              selections: [
                {
                  kind: "Field",
                  name: { kind: "Name", value: "points" },
                  selectionSet: {
                    kind: "SelectionSet",
                    selections: [
                      {
                        kind: "Field",
                        name: { kind: "Name", value: "tsNanos" },
                      },
                      { kind: "Field", name: { kind: "Name", value: "value" } },
                    ],
                  },
                },
              ],
            },
          },
        ],
      },
    },
  ],
} as unknown as DocumentNode<
  RuntimeMetricStripQuery,
  RuntimeMetricStripQueryVariables
>

type Properties<T> = {
  [K in keyof T]: z.ZodType<T[K], T[K] | undefined>
}

type definedNonNullAny = {}

export const isDefinedNonNullAny = (v: any): v is definedNonNullAny =>
  v !== undefined && v !== null

export const definedNonNullAnySchema = z
  .any()
  .refine((v) => isDefinedNonNullAny(v))

export const TraceSortSchema: z.ZodType<
  "DURATION_ASC" | "DURATION_DESC" | "SPAN_COUNT_DESC" | "START_DESC",
  "DURATION_ASC" | "DURATION_DESC" | "SPAN_COUNT_DESC" | "START_DESC"
> = z.enum(["DURATION_ASC", "DURATION_DESC", "SPAN_COUNT_DESC", "START_DESC"])

export const SignalKindSchema: z.ZodType<
  "ERRORS" | "LOGS" | "METRIC_POINTS" | "SPANS" | "TRACES",
  "ERRORS" | "LOGS" | "METRIC_POINTS" | "SPANS" | "TRACES"
> = z.enum(["ERRORS", "LOGS", "METRIC_POINTS", "SPANS", "TRACES"])

export const IssueSortSchema: z.ZodType<
  "EVENTS" | "FIRST_SEEN" | "LAST_SEEN" | "TREND",
  "EVENTS" | "FIRST_SEEN" | "LAST_SEEN" | "TREND"
> = z.enum(["EVENTS", "FIRST_SEEN", "LAST_SEEN", "TREND"])

export const AttributeFilterInputSchema: z.ZodObject<
  Properties<AttributeFilterInput>
> = z.object({
  key: z.string(),
  op: z.string(),
  value: z.string(),
})

export const AlertRuleInputSchema: z.ZodObject<Properties<AlertRuleInput>> =
  z.object({
    attributeFilters: z.string().nullable(),
    comparator: z.string(),
    consecutiveBreachesRequired: z.number().nullable(),
    consecutiveHealthyRequired: z.number().nullable(),
    destinationIds: z.array(z.string()).nullable(),
    enabled: z.boolean().nullable(),
    excludeServices: z.array(z.string()).nullable(),
    groupBy: z.string().nullable(),
    id: z.string().nullable(),
    metricAggregation: z.string().nullable(),
    metricName: z.string().nullable(),
    minimumSampleCount: z.number().nullable(),
    name: z.string(),
    noDataBehavior: z.string().nullable(),
    renotifyIntervalMinutes: z.number().nullable(),
    services: z.array(z.string()).nullable(),
    severity: z.string(),
    signalType: z.string(),
    threshold: z.number(),
    thresholdUpper: z.number().nullable(),
    windowMinutes: z.number(),
  })

export const RuntimeMetricStripQuerySchema: z.ZodType<RuntimeMetricStripQuery> =
  z.object({
    cpu: z.array(
      z.object({
        points: z.array(
          z.object({
            tsNanos: z.string(),
            value: z.number(),
          })
        ),
      })
    ),
    memory: z.array(
      z.object({
        points: z.array(
          z.object({
            tsNanos: z.string(),
            value: z.number(),
          })
        ),
      })
    ),
    tasks: z.array(
      z.object({
        points: z.array(
          z.object({
            tsNanos: z.string(),
            value: z.number(),
          })
        ),
      })
    ),
  })
