/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SqlRouteImport } from './routes/sql'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as EcosystemRouteImport } from './routes/ecosystem'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TracesIndexRouteImport } from './routes/traces.index'
import { Route as IssuesIndexRouteImport } from './routes/issues.index'
import { Route as InvocationsIndexRouteImport } from './routes/invocations.index'
import { Route as InvestigationsIndexRouteImport } from './routes/investigations.index'
import { Route as DashboardsIndexRouteImport } from './routes/dashboards.index'
import { Route as TracesTraceIdRouteImport } from './routes/traces.$traceId'
import { Route as ServicesServiceRouteImport } from './routes/services.$service'
import { Route as IssuesFingerprintRouteImport } from './routes/issues.$fingerprint'
import { Route as InvocationsInvocationIdRouteImport } from './routes/invocations.$invocationId'
import { Route as InvestigationsInvestigationIdRouteImport } from './routes/investigations.$investigationId'
import { Route as DashboardsDashboardIdRouteImport } from './routes/dashboards.$dashboardId'

const SqlRoute = SqlRouteImport.update({
  id: '/sql',
  path: '/sql',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemRoute = EcosystemRouteImport.update({
  id: '/ecosystem',
  path: '/ecosystem',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TracesIndexRoute = TracesIndexRouteImport.update({
  id: '/traces/',
  path: '/traces/',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesIndexRoute = IssuesIndexRouteImport.update({
  id: '/issues/',
  path: '/issues/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvocationsIndexRoute = InvocationsIndexRouteImport.update({
  id: '/invocations/',
  path: '/invocations/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigationsIndexRoute = InvestigationsIndexRouteImport.update({
  id: '/investigations/',
  path: '/investigations/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsIndexRoute = DashboardsIndexRouteImport.update({
  id: '/dashboards/',
  path: '/dashboards/',
  getParentRoute: () => rootRouteImport,
} as any)
const TracesTraceIdRoute = TracesTraceIdRouteImport.update({
  id: '/traces/$traceId',
  path: '/traces/$traceId',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesServiceRoute = ServicesServiceRouteImport.update({
  id: '/$service',
  path: '/$service',
  getParentRoute: () => ServicesRoute,
} as any)
const IssuesFingerprintRoute = IssuesFingerprintRouteImport.update({
  id: '/issues/$fingerprint',
  path: '/issues/$fingerprint',
  getParentRoute: () => rootRouteImport,
} as any)
const InvocationsInvocationIdRoute = InvocationsInvocationIdRouteImport.update({
  id: '/invocations/$invocationId',
  path: '/invocations/$invocationId',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigationsInvestigationIdRoute =
  InvestigationsInvestigationIdRouteImport.update({
    id: '/investigations/$investigationId',
    path: '/investigations/$investigationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardsDashboardIdRoute = DashboardsDashboardIdRouteImport.update({
  id: '/dashboards/$dashboardId',
  path: '/dashboards/$dashboardId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ecosystem': typeof EcosystemRoute
  '/logs': typeof LogsRoute
  '/services': typeof ServicesRouteWithChildren
  '/sql': typeof SqlRoute
  '/dashboards/$dashboardId': typeof DashboardsDashboardIdRoute
  '/investigations/$investigationId': typeof InvestigationsInvestigationIdRoute
  '/invocations/$invocationId': typeof InvocationsInvocationIdRoute
  '/issues/$fingerprint': typeof IssuesFingerprintRoute
  '/services/$service': typeof ServicesServiceRoute
  '/traces/$traceId': typeof TracesTraceIdRoute
  '/dashboards/': typeof DashboardsIndexRoute
  '/investigations/': typeof InvestigationsIndexRoute
  '/invocations/': typeof InvocationsIndexRoute
  '/issues/': typeof IssuesIndexRoute
  '/traces/': typeof TracesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ecosystem': typeof EcosystemRoute
  '/logs': typeof LogsRoute
  '/services': typeof ServicesRouteWithChildren
  '/sql': typeof SqlRoute
  '/dashboards/$dashboardId': typeof DashboardsDashboardIdRoute
  '/investigations/$investigationId': typeof InvestigationsInvestigationIdRoute
  '/invocations/$invocationId': typeof InvocationsInvocationIdRoute
  '/issues/$fingerprint': typeof IssuesFingerprintRoute
  '/services/$service': typeof ServicesServiceRoute
  '/traces/$traceId': typeof TracesTraceIdRoute
  '/dashboards': typeof DashboardsIndexRoute
  '/investigations': typeof InvestigationsIndexRoute
  '/invocations': typeof InvocationsIndexRoute
  '/issues': typeof IssuesIndexRoute
  '/traces': typeof TracesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ecosystem': typeof EcosystemRoute
  '/logs': typeof LogsRoute
  '/services': typeof ServicesRouteWithChildren
  '/sql': typeof SqlRoute
  '/dashboards/$dashboardId': typeof DashboardsDashboardIdRoute
  '/investigations/$investigationId': typeof InvestigationsInvestigationIdRoute
  '/invocations/$invocationId': typeof InvocationsInvocationIdRoute
  '/issues/$fingerprint': typeof IssuesFingerprintRoute
  '/services/$service': typeof ServicesServiceRoute
  '/traces/$traceId': typeof TracesTraceIdRoute
  '/dashboards/': typeof DashboardsIndexRoute
  '/investigations/': typeof InvestigationsIndexRoute
  '/invocations/': typeof InvocationsIndexRoute
  '/issues/': typeof IssuesIndexRoute
  '/traces/': typeof TracesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ecosystem'
    | '/logs'
    | '/services'
    | '/sql'
    | '/dashboards/$dashboardId'
    | '/investigations/$investigationId'
    | '/invocations/$invocationId'
    | '/issues/$fingerprint'
    | '/services/$service'
    | '/traces/$traceId'
    | '/dashboards/'
    | '/investigations/'
    | '/invocations/'
    | '/issues/'
    | '/traces/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ecosystem'
    | '/logs'
    | '/services'
    | '/sql'
    | '/dashboards/$dashboardId'
    | '/investigations/$investigationId'
    | '/invocations/$invocationId'
    | '/issues/$fingerprint'
    | '/services/$service'
    | '/traces/$traceId'
    | '/dashboards'
    | '/investigations'
    | '/invocations'
    | '/issues'
    | '/traces'
  id:
    | '__root__'
    | '/'
    | '/ecosystem'
    | '/logs'
    | '/services'
    | '/sql'
    | '/dashboards/$dashboardId'
    | '/investigations/$investigationId'
    | '/invocations/$invocationId'
    | '/issues/$fingerprint'
    | '/services/$service'
    | '/traces/$traceId'
    | '/dashboards/'
    | '/investigations/'
    | '/invocations/'
    | '/issues/'
    | '/traces/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EcosystemRoute: typeof EcosystemRoute
  LogsRoute: typeof LogsRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SqlRoute: typeof SqlRoute
  DashboardsDashboardIdRoute: typeof DashboardsDashboardIdRoute
  InvestigationsInvestigationIdRoute: typeof InvestigationsInvestigationIdRoute
  InvocationsInvocationIdRoute: typeof InvocationsInvocationIdRoute
  IssuesFingerprintRoute: typeof IssuesFingerprintRoute
  TracesTraceIdRoute: typeof TracesTraceIdRoute
  DashboardsIndexRoute: typeof DashboardsIndexRoute
  InvestigationsIndexRoute: typeof InvestigationsIndexRoute
  InvocationsIndexRoute: typeof InvocationsIndexRoute
  IssuesIndexRoute: typeof IssuesIndexRoute
  TracesIndexRoute: typeof TracesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sql': {
      id: '/sql'
      path: '/sql'
      fullPath: '/sql'
      preLoaderRoute: typeof SqlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem': {
      id: '/ecosystem'
      path: '/ecosystem'
      fullPath: '/ecosystem'
      preLoaderRoute: typeof EcosystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traces/': {
      id: '/traces/'
      path: '/traces'
      fullPath: '/traces/'
      preLoaderRoute: typeof TracesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues/': {
      id: '/issues/'
      path: '/issues'
      fullPath: '/issues/'
      preLoaderRoute: typeof IssuesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invocations/': {
      id: '/invocations/'
      path: '/invocations'
      fullPath: '/invocations/'
      preLoaderRoute: typeof InvocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigations/': {
      id: '/investigations/'
      path: '/investigations'
      fullPath: '/investigations/'
      preLoaderRoute: typeof InvestigationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards/': {
      id: '/dashboards/'
      path: '/dashboards'
      fullPath: '/dashboards/'
      preLoaderRoute: typeof DashboardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traces/$traceId': {
      id: '/traces/$traceId'
      path: '/traces/$traceId'
      fullPath: '/traces/$traceId'
      preLoaderRoute: typeof TracesTraceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$service': {
      id: '/services/$service'
      path: '/$service'
      fullPath: '/services/$service'
      preLoaderRoute: typeof ServicesServiceRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/issues/$fingerprint': {
      id: '/issues/$fingerprint'
      path: '/issues/$fingerprint'
      fullPath: '/issues/$fingerprint'
      preLoaderRoute: typeof IssuesFingerprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invocations/$invocationId': {
      id: '/invocations/$invocationId'
      path: '/invocations/$invocationId'
      fullPath: '/invocations/$invocationId'
      preLoaderRoute: typeof InvocationsInvocationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigations/$investigationId': {
      id: '/investigations/$investigationId'
      path: '/investigations/$investigationId'
      fullPath: '/investigations/$investigationId'
      preLoaderRoute: typeof InvestigationsInvestigationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards/$dashboardId': {
      id: '/dashboards/$dashboardId'
      path: '/dashboards/$dashboardId'
      fullPath: '/dashboards/$dashboardId'
      preLoaderRoute: typeof DashboardsDashboardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ServicesRouteChildren {
  ServicesServiceRoute: typeof ServicesServiceRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesServiceRoute: ServicesServiceRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EcosystemRoute: EcosystemRoute,
  LogsRoute: LogsRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SqlRoute: SqlRoute,
  DashboardsDashboardIdRoute: DashboardsDashboardIdRoute,
  InvestigationsInvestigationIdRoute: InvestigationsInvestigationIdRoute,
  InvocationsInvocationIdRoute: InvocationsInvocationIdRoute,
  IssuesFingerprintRoute: IssuesFingerprintRoute,
  TracesTraceIdRoute: TracesTraceIdRoute,
  DashboardsIndexRoute: DashboardsIndexRoute,
  InvestigationsIndexRoute: InvestigationsIndexRoute,
  InvocationsIndexRoute: InvocationsIndexRoute,
  IssuesIndexRoute: IssuesIndexRoute,
  TracesIndexRoute: TracesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
