/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SqlRouteImport } from './routes/sql'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TracesIndexRouteImport } from './routes/traces.index'
import { Route as RunsIndexRouteImport } from './routes/runs.index'
import { Route as IssuesIndexRouteImport } from './routes/issues.index'
import { Route as DashboardsIndexRouteImport } from './routes/dashboards.index'
import { Route as TracesTraceIdRouteImport } from './routes/traces.$traceId'
import { Route as RunsRunIdRouteImport } from './routes/runs.$runId'
import { Route as IssuesFingerprintRouteImport } from './routes/issues.$fingerprint'
import { Route as DashboardsDashboardIdRouteImport } from './routes/dashboards.$dashboardId'

const SqlRoute = SqlRouteImport.update({
  id: '/sql',
  path: '/sql',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TracesIndexRoute = TracesIndexRouteImport.update({
  id: '/traces/',
  path: '/traces/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsIndexRoute = RunsIndexRouteImport.update({
  id: '/runs/',
  path: '/runs/',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesIndexRoute = IssuesIndexRouteImport.update({
  id: '/issues/',
  path: '/issues/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsIndexRoute = DashboardsIndexRouteImport.update({
  id: '/dashboards/',
  path: '/dashboards/',
  getParentRoute: () => rootRouteImport,
} as any)
const TracesTraceIdRoute = TracesTraceIdRouteImport.update({
  id: '/traces/$traceId',
  path: '/traces/$traceId',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIdRoute = RunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesFingerprintRoute = IssuesFingerprintRouteImport.update({
  id: '/issues/$fingerprint',
  path: '/issues/$fingerprint',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsDashboardIdRoute = DashboardsDashboardIdRouteImport.update({
  id: '/dashboards/$dashboardId',
  path: '/dashboards/$dashboardId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/logs': typeof LogsRoute
  '/services': typeof ServicesRoute
  '/sql': typeof SqlRoute
  '/dashboards/$dashboardId': typeof DashboardsDashboardIdRoute
  '/issues/$fingerprint': typeof IssuesFingerprintRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/traces/$traceId': typeof TracesTraceIdRoute
  '/dashboards/': typeof DashboardsIndexRoute
  '/issues/': typeof IssuesIndexRoute
  '/runs/': typeof RunsIndexRoute
  '/traces/': typeof TracesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/logs': typeof LogsRoute
  '/services': typeof ServicesRoute
  '/sql': typeof SqlRoute
  '/dashboards/$dashboardId': typeof DashboardsDashboardIdRoute
  '/issues/$fingerprint': typeof IssuesFingerprintRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/traces/$traceId': typeof TracesTraceIdRoute
  '/dashboards': typeof DashboardsIndexRoute
  '/issues': typeof IssuesIndexRoute
  '/runs': typeof RunsIndexRoute
  '/traces': typeof TracesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/logs': typeof LogsRoute
  '/services': typeof ServicesRoute
  '/sql': typeof SqlRoute
  '/dashboards/$dashboardId': typeof DashboardsDashboardIdRoute
  '/issues/$fingerprint': typeof IssuesFingerprintRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/traces/$traceId': typeof TracesTraceIdRoute
  '/dashboards/': typeof DashboardsIndexRoute
  '/issues/': typeof IssuesIndexRoute
  '/runs/': typeof RunsIndexRoute
  '/traces/': typeof TracesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/logs'
    | '/services'
    | '/sql'
    | '/dashboards/$dashboardId'
    | '/issues/$fingerprint'
    | '/runs/$runId'
    | '/traces/$traceId'
    | '/dashboards/'
    | '/issues/'
    | '/runs/'
    | '/traces/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/logs'
    | '/services'
    | '/sql'
    | '/dashboards/$dashboardId'
    | '/issues/$fingerprint'
    | '/runs/$runId'
    | '/traces/$traceId'
    | '/dashboards'
    | '/issues'
    | '/runs'
    | '/traces'
  id:
    | '__root__'
    | '/'
    | '/logs'
    | '/services'
    | '/sql'
    | '/dashboards/$dashboardId'
    | '/issues/$fingerprint'
    | '/runs/$runId'
    | '/traces/$traceId'
    | '/dashboards/'
    | '/issues/'
    | '/runs/'
    | '/traces/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LogsRoute: typeof LogsRoute
  ServicesRoute: typeof ServicesRoute
  SqlRoute: typeof SqlRoute
  DashboardsDashboardIdRoute: typeof DashboardsDashboardIdRoute
  IssuesFingerprintRoute: typeof IssuesFingerprintRoute
  RunsRunIdRoute: typeof RunsRunIdRoute
  TracesTraceIdRoute: typeof TracesTraceIdRoute
  DashboardsIndexRoute: typeof DashboardsIndexRoute
  IssuesIndexRoute: typeof IssuesIndexRoute
  RunsIndexRoute: typeof RunsIndexRoute
  TracesIndexRoute: typeof TracesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sql': {
      id: '/sql'
      path: '/sql'
      fullPath: '/sql'
      preLoaderRoute: typeof SqlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traces/': {
      id: '/traces/'
      path: '/traces'
      fullPath: '/traces/'
      preLoaderRoute: typeof TracesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/': {
      id: '/runs/'
      path: '/runs'
      fullPath: '/runs/'
      preLoaderRoute: typeof RunsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues/': {
      id: '/issues/'
      path: '/issues'
      fullPath: '/issues/'
      preLoaderRoute: typeof IssuesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards/': {
      id: '/dashboards/'
      path: '/dashboards'
      fullPath: '/dashboards/'
      preLoaderRoute: typeof DashboardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traces/$traceId': {
      id: '/traces/$traceId'
      path: '/traces/$traceId'
      fullPath: '/traces/$traceId'
      preLoaderRoute: typeof TracesTraceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$runId': {
      id: '/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof RunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues/$fingerprint': {
      id: '/issues/$fingerprint'
      path: '/issues/$fingerprint'
      fullPath: '/issues/$fingerprint'
      preLoaderRoute: typeof IssuesFingerprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards/$dashboardId': {
      id: '/dashboards/$dashboardId'
      path: '/dashboards/$dashboardId'
      fullPath: '/dashboards/$dashboardId'
      preLoaderRoute: typeof DashboardsDashboardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LogsRoute: LogsRoute,
  ServicesRoute: ServicesRoute,
  SqlRoute: SqlRoute,
  DashboardsDashboardIdRoute: DashboardsDashboardIdRoute,
  IssuesFingerprintRoute: IssuesFingerprintRoute,
  RunsRunIdRoute: RunsRunIdRoute,
  TracesTraceIdRoute: TracesTraceIdRoute,
  DashboardsIndexRoute: DashboardsIndexRoute,
  IssuesIndexRoute: IssuesIndexRoute,
  RunsIndexRoute: RunsIndexRoute,
  TracesIndexRoute: TracesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
