/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as EcosystemRouteImport } from './routes/ecosystem'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SqlRouteImport } from './routes/sql'
import { Route as AlertsIndexRouteImport } from './routes/alerts.index'
import { Route as DashboardsIndexRouteImport } from './routes/dashboards.index'
import { Route as DashboardsDashboardIdRouteImport } from './routes/dashboards.$dashboardId'
import { Route as InvestigationsIndexRouteImport } from './routes/investigations.index'
import { Route as InvestigationsInvestigationIdRouteImport } from './routes/investigations.$investigationId'
import { Route as InvocationsIndexRouteImport } from './routes/invocations.index'
import { Route as InvocationsInvocationIdRouteImport } from './routes/invocations.$invocationId'
import { Route as IssuesIndexRouteImport } from './routes/issues.index'
import { Route as MetricsIndexRouteImport } from './routes/metrics.index'
import { Route as MetricsMetricNameRouteImport } from './routes/metrics.$metricName'
import { Route as RumIndexRouteImport } from './routes/rum.index'
import { Route as ServicesServiceRouteImport } from './routes/services.$service'
import { Route as TestsIndexRouteImport } from './routes/tests.index'
import { Route as TestsCaseKeyRouteImport } from './routes/tests.$caseKey'
import { Route as TracesIndexRouteImport } from './routes/traces.index'
import { Route as TracesTraceIdRouteImport } from './routes/traces.$traceId'
import { Route as IssuesServiceFingerprintRouteImport } from './routes/issues.$service.$fingerprint'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemRoute = EcosystemRouteImport.update({
  id: '/ecosystem',
  path: '/ecosystem',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SqlRoute = SqlRouteImport.update({
  id: '/sql',
  path: '/sql',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsIndexRoute = AlertsIndexRouteImport.update({
  id: '/alerts/',
  path: '/alerts/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsIndexRoute = DashboardsIndexRouteImport.update({
  id: '/dashboards/',
  path: '/dashboards/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsDashboardIdRoute = DashboardsDashboardIdRouteImport.update({
  id: '/dashboards/$dashboardId',
  path: '/dashboards/$dashboardId',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigationsIndexRoute = InvestigationsIndexRouteImport.update({
  id: '/investigations/',
  path: '/investigations/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigationsInvestigationIdRoute =
  InvestigationsInvestigationIdRouteImport.update({
    id: '/investigations/$investigationId',
    path: '/investigations/$investigationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const InvocationsIndexRoute = InvocationsIndexRouteImport.update({
  id: '/invocations/',
  path: '/invocations/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvocationsInvocationIdRoute = InvocationsInvocationIdRouteImport.update({
  id: '/invocations/$invocationId',
  path: '/invocations/$invocationId',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesIndexRoute = IssuesIndexRouteImport.update({
  id: '/issues/',
  path: '/issues/',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsIndexRoute = MetricsIndexRouteImport.update({
  id: '/metrics/',
  path: '/metrics/',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsMetricNameRoute = MetricsMetricNameRouteImport.update({
  id: '/metrics/$metricName',
  path: '/metrics/$metricName',
  getParentRoute: () => rootRouteImport,
} as any)
const RumIndexRoute = RumIndexRouteImport.update({
  id: '/rum/',
  path: '/rum/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesServiceRoute = ServicesServiceRouteImport.update({
  id: '/$service',
  path: '/$service',
  getParentRoute: () => ServicesRoute,
} as any)
const TestsIndexRoute = TestsIndexRouteImport.update({
  id: '/tests/',
  path: '/tests/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsCaseKeyRoute = TestsCaseKeyRouteImport.update({
  id: '/tests/$caseKey',
  path: '/tests/$caseKey',
  getParentRoute: () => rootRouteImport,
} as any)
const TracesIndexRoute = TracesIndexRouteImport.update({
  id: '/traces/',
  path: '/traces/',
  getParentRoute: () => rootRouteImport,
} as any)
const TracesTraceIdRoute = TracesTraceIdRouteImport.update({
  id: '/traces/$traceId',
  path: '/traces/$traceId',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesServiceFingerprintRoute =
  IssuesServiceFingerprintRouteImport.update({
    id: '/issues/$service/$fingerprint',
    path: '/issues/$service/$fingerprint',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/ecosystem': typeof EcosystemRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/pipeline': typeof PipelineRoute
  '/services': typeof ServicesRouteWithChildren
  '/sql': typeof SqlRoute
  '/dashboards/$dashboardId': typeof DashboardsDashboardIdRoute
  '/investigations/$investigationId': typeof InvestigationsInvestigationIdRoute
  '/invocations/$invocationId': typeof InvocationsInvocationIdRoute
  '/metrics/$metricName': typeof MetricsMetricNameRoute
  '/services/$service': typeof ServicesServiceRoute
  '/tests/$caseKey': typeof TestsCaseKeyRoute
  '/traces/$traceId': typeof TracesTraceIdRoute
  '/alerts/': typeof AlertsIndexRoute
  '/dashboards/': typeof DashboardsIndexRoute
  '/investigations/': typeof InvestigationsIndexRoute
  '/invocations/': typeof InvocationsIndexRoute
  '/issues/': typeof IssuesIndexRoute
  '/metrics/': typeof MetricsIndexRoute
  '/rum/': typeof RumIndexRoute
  '/tests/': typeof TestsIndexRoute
  '/traces/': typeof TracesIndexRoute
  '/issues/$service/$fingerprint': typeof IssuesServiceFingerprintRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/ecosystem': typeof EcosystemRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/pipeline': typeof PipelineRoute
  '/services': typeof ServicesRouteWithChildren
  '/sql': typeof SqlRoute
  '/dashboards/$dashboardId': typeof DashboardsDashboardIdRoute
  '/investigations/$investigationId': typeof InvestigationsInvestigationIdRoute
  '/invocations/$invocationId': typeof InvocationsInvocationIdRoute
  '/metrics/$metricName': typeof MetricsMetricNameRoute
  '/services/$service': typeof ServicesServiceRoute
  '/tests/$caseKey': typeof TestsCaseKeyRoute
  '/traces/$traceId': typeof TracesTraceIdRoute
  '/alerts': typeof AlertsIndexRoute
  '/dashboards': typeof DashboardsIndexRoute
  '/investigations': typeof InvestigationsIndexRoute
  '/invocations': typeof InvocationsIndexRoute
  '/issues': typeof IssuesIndexRoute
  '/metrics': typeof MetricsIndexRoute
  '/rum': typeof RumIndexRoute
  '/tests': typeof TestsIndexRoute
  '/traces': typeof TracesIndexRoute
  '/issues/$service/$fingerprint': typeof IssuesServiceFingerprintRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/ecosystem': typeof EcosystemRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/pipeline': typeof PipelineRoute
  '/services': typeof ServicesRouteWithChildren
  '/sql': typeof SqlRoute
  '/dashboards/$dashboardId': typeof DashboardsDashboardIdRoute
  '/investigations/$investigationId': typeof InvestigationsInvestigationIdRoute
  '/invocations/$invocationId': typeof InvocationsInvocationIdRoute
  '/metrics/$metricName': typeof MetricsMetricNameRoute
  '/services/$service': typeof ServicesServiceRoute
  '/tests/$caseKey': typeof TestsCaseKeyRoute
  '/traces/$traceId': typeof TracesTraceIdRoute
  '/alerts/': typeof AlertsIndexRoute
  '/dashboards/': typeof DashboardsIndexRoute
  '/investigations/': typeof InvestigationsIndexRoute
  '/invocations/': typeof InvocationsIndexRoute
  '/issues/': typeof IssuesIndexRoute
  '/metrics/': typeof MetricsIndexRoute
  '/rum/': typeof RumIndexRoute
  '/tests/': typeof TestsIndexRoute
  '/traces/': typeof TracesIndexRoute
  '/issues/$service/$fingerprint': typeof IssuesServiceFingerprintRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/ecosystem'
    | '/login'
    | '/logs'
    | '/pipeline'
    | '/services'
    | '/sql'
    | '/dashboards/$dashboardId'
    | '/investigations/$investigationId'
    | '/invocations/$invocationId'
    | '/metrics/$metricName'
    | '/services/$service'
    | '/tests/$caseKey'
    | '/traces/$traceId'
    | '/alerts/'
    | '/dashboards/'
    | '/investigations/'
    | '/invocations/'
    | '/issues/'
    | '/metrics/'
    | '/rum/'
    | '/tests/'
    | '/traces/'
    | '/issues/$service/$fingerprint'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/ecosystem'
    | '/login'
    | '/logs'
    | '/pipeline'
    | '/services'
    | '/sql'
    | '/dashboards/$dashboardId'
    | '/investigations/$investigationId'
    | '/invocations/$invocationId'
    | '/metrics/$metricName'
    | '/services/$service'
    | '/tests/$caseKey'
    | '/traces/$traceId'
    | '/alerts'
    | '/dashboards'
    | '/investigations'
    | '/invocations'
    | '/issues'
    | '/metrics'
    | '/rum'
    | '/tests'
    | '/traces'
    | '/issues/$service/$fingerprint'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/ecosystem'
    | '/login'
    | '/logs'
    | '/pipeline'
    | '/services'
    | '/sql'
    | '/dashboards/$dashboardId'
    | '/investigations/$investigationId'
    | '/invocations/$invocationId'
    | '/metrics/$metricName'
    | '/services/$service'
    | '/tests/$caseKey'
    | '/traces/$traceId'
    | '/alerts/'
    | '/dashboards/'
    | '/investigations/'
    | '/invocations/'
    | '/issues/'
    | '/metrics/'
    | '/rum/'
    | '/tests/'
    | '/traces/'
    | '/issues/$service/$fingerprint'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  EcosystemRoute: typeof EcosystemRoute
  LoginRoute: typeof LoginRoute
  LogsRoute: typeof LogsRoute
  PipelineRoute: typeof PipelineRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SqlRoute: typeof SqlRoute
  DashboardsDashboardIdRoute: typeof DashboardsDashboardIdRoute
  InvestigationsInvestigationIdRoute: typeof InvestigationsInvestigationIdRoute
  InvocationsInvocationIdRoute: typeof InvocationsInvocationIdRoute
  MetricsMetricNameRoute: typeof MetricsMetricNameRoute
  TestsCaseKeyRoute: typeof TestsCaseKeyRoute
  TracesTraceIdRoute: typeof TracesTraceIdRoute
  AlertsIndexRoute: typeof AlertsIndexRoute
  DashboardsIndexRoute: typeof DashboardsIndexRoute
  InvestigationsIndexRoute: typeof InvestigationsIndexRoute
  InvocationsIndexRoute: typeof InvocationsIndexRoute
  IssuesIndexRoute: typeof IssuesIndexRoute
  MetricsIndexRoute: typeof MetricsIndexRoute
  RumIndexRoute: typeof RumIndexRoute
  TestsIndexRoute: typeof TestsIndexRoute
  TracesIndexRoute: typeof TracesIndexRoute
  IssuesServiceFingerprintRoute: typeof IssuesServiceFingerprintRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem': {
      id: '/ecosystem'
      path: '/ecosystem'
      fullPath: '/ecosystem'
      preLoaderRoute: typeof EcosystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sql': {
      id: '/sql'
      path: '/sql'
      fullPath: '/sql'
      preLoaderRoute: typeof SqlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts/': {
      id: '/alerts/'
      path: '/alerts'
      fullPath: '/alerts/'
      preLoaderRoute: typeof AlertsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards/': {
      id: '/dashboards/'
      path: '/dashboards'
      fullPath: '/dashboards/'
      preLoaderRoute: typeof DashboardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards/$dashboardId': {
      id: '/dashboards/$dashboardId'
      path: '/dashboards/$dashboardId'
      fullPath: '/dashboards/$dashboardId'
      preLoaderRoute: typeof DashboardsDashboardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigations/': {
      id: '/investigations/'
      path: '/investigations'
      fullPath: '/investigations/'
      preLoaderRoute: typeof InvestigationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigations/$investigationId': {
      id: '/investigations/$investigationId'
      path: '/investigations/$investigationId'
      fullPath: '/investigations/$investigationId'
      preLoaderRoute: typeof InvestigationsInvestigationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invocations/': {
      id: '/invocations/'
      path: '/invocations'
      fullPath: '/invocations/'
      preLoaderRoute: typeof InvocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invocations/$invocationId': {
      id: '/invocations/$invocationId'
      path: '/invocations/$invocationId'
      fullPath: '/invocations/$invocationId'
      preLoaderRoute: typeof InvocationsInvocationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues/': {
      id: '/issues/'
      path: '/issues'
      fullPath: '/issues/'
      preLoaderRoute: typeof IssuesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics/': {
      id: '/metrics/'
      path: '/metrics'
      fullPath: '/metrics/'
      preLoaderRoute: typeof MetricsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics/$metricName': {
      id: '/metrics/$metricName'
      path: '/metrics/$metricName'
      fullPath: '/metrics/$metricName'
      preLoaderRoute: typeof MetricsMetricNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rum/': {
      id: '/rum/'
      path: '/rum'
      fullPath: '/rum/'
      preLoaderRoute: typeof RumIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$service': {
      id: '/services/$service'
      path: '/$service'
      fullPath: '/services/$service'
      preLoaderRoute: typeof ServicesServiceRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/tests/': {
      id: '/tests/'
      path: '/tests'
      fullPath: '/tests/'
      preLoaderRoute: typeof TestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/$caseKey': {
      id: '/tests/$caseKey'
      path: '/tests/$caseKey'
      fullPath: '/tests/$caseKey'
      preLoaderRoute: typeof TestsCaseKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traces/': {
      id: '/traces/'
      path: '/traces'
      fullPath: '/traces/'
      preLoaderRoute: typeof TracesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traces/$traceId': {
      id: '/traces/$traceId'
      path: '/traces/$traceId'
      fullPath: '/traces/$traceId'
      preLoaderRoute: typeof TracesTraceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues/$service/$fingerprint': {
      id: '/issues/$service/$fingerprint'
      path: '/issues/$service/$fingerprint'
      fullPath: '/issues/$service/$fingerprint'
      preLoaderRoute: typeof IssuesServiceFingerprintRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ServicesRouteChildren {
  ServicesServiceRoute: typeof ServicesServiceRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesServiceRoute: ServicesServiceRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  EcosystemRoute: EcosystemRoute,
  LoginRoute: LoginRoute,
  LogsRoute: LogsRoute,
  PipelineRoute: PipelineRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SqlRoute: SqlRoute,
  DashboardsDashboardIdRoute: DashboardsDashboardIdRoute,
  InvestigationsInvestigationIdRoute: InvestigationsInvestigationIdRoute,
  InvocationsInvocationIdRoute: InvocationsInvocationIdRoute,
  MetricsMetricNameRoute: MetricsMetricNameRoute,
  TestsCaseKeyRoute: TestsCaseKeyRoute,
  TracesTraceIdRoute: TracesTraceIdRoute,
  AlertsIndexRoute: AlertsIndexRoute,
  DashboardsIndexRoute: DashboardsIndexRoute,
  InvestigationsIndexRoute: InvestigationsIndexRoute,
  InvocationsIndexRoute: InvocationsIndexRoute,
  IssuesIndexRoute: IssuesIndexRoute,
  MetricsIndexRoute: MetricsIndexRoute,
  RumIndexRoute: RumIndexRoute,
  TestsIndexRoute: TestsIndexRoute,
  TracesIndexRoute: TracesIndexRoute,
  IssuesServiceFingerprintRoute: IssuesServiceFingerprintRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
