/* AUTO-GENERATED by GraphQL Code Generator — DO NOT EDIT. Plan 152. */
// @ts-nocheck

/** Internal type. DO NOT USE DIRECTLY. */
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] }
/** Internal type. DO NOT USE DIRECTLY. */
export type Incremental<T> =
  | T
  | {
      [P in keyof T]?: P extends " $fragmentName" | "__typename" ? T[P] : never
    }
import type * as Types from "../../../platform/graphql/generated/schema-types.generated"

import * as z from "zod"
import type {
  TraceSort,
  SignalKind,
  IssueSort,
  AttributeFilterInput,
  AlertRuleInput,
  ServicesListQuery,
} from "@/platform/graphql/generated/schema-types.generated"
import type { TypedDocumentNode as DocumentNode } from "@/platform/graphql/typed-document"
export type ServicesListQueryVariables = Exact<{
  fromNanos: string
  toNanos: string
}>

export type ServicesListQuery = {
  readonly serviceList: ReadonlyArray<{
    readonly name: string
    readonly lastSeenNanos: string
    readonly spanCount: string
    readonly errorCount: string
    readonly p95Ms: number | null
  }>
  readonly serviceCatalog: ReadonlyArray<{
    readonly name: string
    readonly serviceVersion: string | null
    readonly serviceNamespace: string | null
    readonly deploymentEnvironment: string | null
    readonly telemetrySdkLanguage: string | null
    readonly telemetrySdkName: string | null
    readonly telemetrySdkVersion: string | null
    readonly lastSeenNanos: string
    readonly instanceCount: string
  }>
}

export const ServicesListDocument = {
  kind: "Document",
  definitions: [
    {
      kind: "OperationDefinition",
      operation: "query",
      name: { kind: "Name", value: "ServicesList" },
      variableDefinitions: [
        {
          kind: "VariableDefinition",
          variable: {
            kind: "Variable",
            name: { kind: "Name", value: "fromNanos" },
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: { kind: "Name", value: "String" },
            },
          },
        },
        {
          kind: "VariableDefinition",
          variable: {
            kind: "Variable",
            name: { kind: "Name", value: "toNanos" },
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: { kind: "Name", value: "String" },
            },
          },
        },
      ],
      selectionSet: {
        kind: "SelectionSet",
        selections: [
          {
            kind: "Field",
            name: { kind: "Name", value: "serviceList" },
            arguments: [
              {
                kind: "Argument",
                name: { kind: "Name", value: "fromNanos" },
                value: {
                  kind: "Variable",
                  name: { kind: "Name", value: "fromNanos" },
                },
              },
              {
                kind: "Argument",
                name: { kind: "Name", value: "toNanos" },
                value: {
                  kind: "Variable",
                  name: { kind: "Name", value: "toNanos" },
                },
              },
            ],
            selectionSet: {
              kind: "SelectionSet",
              selections: [
                { kind: "Field", name: { kind: "Name", value: "name" } },
                {
                  kind: "Field",
                  name: { kind: "Name", value: "lastSeenNanos" },
                },
                { kind: "Field", name: { kind: "Name", value: "spanCount" } },
                { kind: "Field", name: { kind: "Name", value: "errorCount" } },
                { kind: "Field", name: { kind: "Name", value: "p95Ms" } },
              ],
            },
          },
          {
            kind: "Field",
            name: { kind: "Name", value: "serviceCatalog" },
            arguments: [
              {
                kind: "Argument",
                name: { kind: "Name", value: "fromNanos" },
                value: {
                  kind: "Variable",
                  name: { kind: "Name", value: "fromNanos" },
                },
              },
              {
                kind: "Argument",
                name: { kind: "Name", value: "toNanos" },
                value: {
                  kind: "Variable",
                  name: { kind: "Name", value: "toNanos" },
                },
              },
            ],
            selectionSet: {
              kind: "SelectionSet",
              selections: [
                { kind: "Field", name: { kind: "Name", value: "name" } },
                {
                  kind: "Field",
                  name: { kind: "Name", value: "serviceVersion" },
                },
                {
                  kind: "Field",
                  name: { kind: "Name", value: "serviceNamespace" },
                },
                {
                  kind: "Field",
                  name: { kind: "Name", value: "deploymentEnvironment" },
                },
                {
                  kind: "Field",
                  name: { kind: "Name", value: "telemetrySdkLanguage" },
                },
                {
                  kind: "Field",
                  name: { kind: "Name", value: "telemetrySdkName" },
                },
                {
                  kind: "Field",
                  name: { kind: "Name", value: "telemetrySdkVersion" },
                },
                {
                  kind: "Field",
                  name: { kind: "Name", value: "lastSeenNanos" },
                },
                {
                  kind: "Field",
                  name: { kind: "Name", value: "instanceCount" },
                },
              ],
            },
          },
        ],
      },
    },
  ],
} as unknown as DocumentNode<ServicesListQuery, ServicesListQueryVariables>

type Properties<T> = {
  [K in keyof T]: z.ZodType<T[K], T[K] | undefined>
}

type definedNonNullAny = {}

export const isDefinedNonNullAny = (v: any): v is definedNonNullAny =>
  v !== undefined && v !== null

export const definedNonNullAnySchema = z
  .any()
  .refine((v) => isDefinedNonNullAny(v))

export const TraceSortSchema: z.ZodType<
  "DURATION_ASC" | "DURATION_DESC" | "SPAN_COUNT_DESC" | "START_DESC",
  "DURATION_ASC" | "DURATION_DESC" | "SPAN_COUNT_DESC" | "START_DESC"
> = z.enum(["DURATION_ASC", "DURATION_DESC", "SPAN_COUNT_DESC", "START_DESC"])

export const SignalKindSchema: z.ZodType<
  "ERRORS" | "LOGS" | "METRIC_POINTS" | "SPANS" | "TRACES",
  "ERRORS" | "LOGS" | "METRIC_POINTS" | "SPANS" | "TRACES"
> = z.enum(["ERRORS", "LOGS", "METRIC_POINTS", "SPANS", "TRACES"])

export const IssueSortSchema: z.ZodType<
  "EVENTS" | "FIRST_SEEN" | "LAST_SEEN" | "TREND",
  "EVENTS" | "FIRST_SEEN" | "LAST_SEEN" | "TREND"
> = z.enum(["EVENTS", "FIRST_SEEN", "LAST_SEEN", "TREND"])

export const AttributeFilterInputSchema: z.ZodObject<
  Properties<AttributeFilterInput>
> = z.object({
  key: z.string(),
  op: z.string(),
  value: z.string(),
})

export const AlertRuleInputSchema: z.ZodObject<Properties<AlertRuleInput>> =
  z.object({
    attributeFilters: z.string().nullable(),
    comparator: z.string(),
    consecutiveBreachesRequired: z.number().nullable(),
    consecutiveHealthyRequired: z.number().nullable(),
    destinationIds: z.array(z.string()).nullable(),
    enabled: z.boolean().nullable(),
    excludeServices: z.array(z.string()).nullable(),
    groupBy: z.string().nullable(),
    id: z.string().nullable(),
    metricAggregation: z.string().nullable(),
    metricName: z.string().nullable(),
    minimumSampleCount: z.number().nullable(),
    name: z.string(),
    noDataBehavior: z.string().nullable(),
    renotifyIntervalMinutes: z.number().nullable(),
    services: z.array(z.string()).nullable(),
    severity: z.string(),
    signalType: z.string(),
    threshold: z.number(),
    thresholdUpper: z.number().nullable(),
    windowMinutes: z.number(),
  })

export const ServicesListQuerySchema: z.ZodType<ServicesListQuery> = z.object({
  serviceList: z.array(
    z.object({
      name: z.string(),
      lastSeenNanos: z.string(),
      spanCount: z.string(),
      errorCount: z.string(),
      p95Ms: z.number().nullable(),
    })
  ),
  serviceCatalog: z.array(
    z.object({
      name: z.string(),
      serviceVersion: z.string().nullable(),
      serviceNamespace: z.string().nullable(),
      deploymentEnvironment: z.string().nullable(),
      telemetrySdkLanguage: z.string().nullable(),
      telemetrySdkName: z.string().nullable(),
      telemetrySdkVersion: z.string().nullable(),
      lastSeenNanos: z.string(),
      instanceCount: z.string(),
    })
  ),
})
