/* AUTO-GENERATED by GraphQL Code Generator — DO NOT EDIT. Plan 152. */
// @ts-nocheck

/** Internal type. DO NOT USE DIRECTLY. */
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] }
/** Internal type. DO NOT USE DIRECTLY. */
export type Incremental<T> =
  | T
  | { [P in keyof T]?: P extends " $fragmentName" | "__typename" ? T[P] : never }
import type * as Types from "../../../platform/graphql/generated/schema-types.generated"

import * as z from "zod"
import type {
  TraceSort,
  TestResultStatus,
  TestFlakyState,
  TestExplorerSort,
  TestRollup,
  TestConfigurationFilterInput,
  TestIdentitySource,
  SignalKind,
  IssueSort,
  AttributeFilterInput,
  AlertRuleInput,
  ServiceDetailQuery,
} from "@/platform/graphql/generated/schema-types.generated"
import type { TypedDocumentNode as DocumentNode } from "@/platform/graphql/typed-document"
export type ServiceDetailQueryVariables = Exact<{
  service: string
  fromNanos: string
  toNanos: string
  stepSeconds: number
  httpDurationMetric: string
  rpcDurationMetric: string
}>

export type ServiceDetailQuery = {
  readonly red: {
    readonly rate: ReadonlyArray<{ readonly tsNanos: string; readonly value: number }>
    readonly errorRate: ReadonlyArray<{ readonly tsNanos: string; readonly value: number }>
    readonly p50: ReadonlyArray<{ readonly tsNanos: string; readonly value: number }>
    readonly p95: ReadonlyArray<{ readonly tsNanos: string; readonly value: number }>
    readonly p99: ReadonlyArray<{ readonly tsNanos: string; readonly value: number }>
  }
  readonly overview: {
    readonly cpu: ReadonlyArray<{ readonly tsNanos: string; readonly value: number }>
    readonly memory: ReadonlyArray<{ readonly tsNanos: string; readonly value: number }>
    readonly requestRate: ReadonlyArray<{ readonly tsNanos: string; readonly value: number }>
    readonly errorRate: ReadonlyArray<{ readonly tsNanos: string; readonly value: number }>
    readonly latencyP50: ReadonlyArray<{ readonly tsNanos: string; readonly value: number }>
    readonly latencyP95: ReadonlyArray<{ readonly tsNanos: string; readonly value: number }>
    readonly latencyP99: ReadonlyArray<{ readonly tsNanos: string; readonly value: number }>
  }
  readonly releases: ReadonlyArray<{
    readonly version: string
    readonly firstSeenNanos: string
    readonly lastSeenNanos: string
    readonly spanCount: string
  }>
  readonly serviceCatalog: ReadonlyArray<{
    readonly name: string
    readonly serviceVersion: string | null
    readonly serviceNamespace: string | null
    readonly deploymentEnvironment: string | null
    readonly telemetrySdkLanguage: string | null
    readonly telemetrySdkName: string | null
    readonly telemetrySdkVersion: string | null
    readonly lastSeenNanos: string
    readonly instanceCount: string
  }>
  readonly httpDurationExemplars: ReadonlyArray<{
    readonly tsNanos: string
    readonly service: string
    readonly name: string
    readonly value: number
    readonly traceId: string
    readonly spanId: string
    readonly invocationId: string | null
    readonly attributes: string
  }>
  readonly rpcDurationExemplars: ReadonlyArray<{
    readonly tsNanos: string
    readonly service: string
    readonly name: string
    readonly value: number
    readonly traceId: string
    readonly spanId: string
    readonly invocationId: string | null
    readonly attributes: string
  }>
  readonly runtimeSnapshot: ReadonlyArray<{
    readonly family: string
    readonly metric: string
    readonly unit: string | null
    readonly points: ReadonlyArray<{ readonly tsNanos: string; readonly value: number }>
  }>
  readonly tracesPage: {
    readonly items: ReadonlyArray<{
      readonly traceId: string
      readonly rootName: string
      readonly service: string
      readonly startNanos: string
      readonly durationNs: string
      readonly spanCount: number
      readonly hasError: boolean
    }>
  }
}

export const ServiceDetailDocument = {
  kind: "Document",
  definitions: [
    {
      kind: "OperationDefinition",
      operation: "query",
      name: { kind: "Name", value: "ServiceDetail" },
      variableDefinitions: [
        {
          kind: "VariableDefinition",
          variable: { kind: "Variable", name: { kind: "Name", value: "service" } },
          type: {
            kind: "NonNullType",
            type: { kind: "NamedType", name: { kind: "Name", value: "String" } },
          },
        },
        {
          kind: "VariableDefinition",
          variable: { kind: "Variable", name: { kind: "Name", value: "fromNanos" } },
          type: {
            kind: "NonNullType",
            type: { kind: "NamedType", name: { kind: "Name", value: "String" } },
          },
        },
        {
          kind: "VariableDefinition",
          variable: { kind: "Variable", name: { kind: "Name", value: "toNanos" } },
          type: {
            kind: "NonNullType",
            type: { kind: "NamedType", name: { kind: "Name", value: "String" } },
          },
        },
        {
          kind: "VariableDefinition",
          variable: { kind: "Variable", name: { kind: "Name", value: "stepSeconds" } },
          type: {
            kind: "NonNullType",
            type: { kind: "NamedType", name: { kind: "Name", value: "Int" } },
          },
        },
        {
          kind: "VariableDefinition",
          variable: { kind: "Variable", name: { kind: "Name", value: "httpDurationMetric" } },
          type: {
            kind: "NonNullType",
            type: { kind: "NamedType", name: { kind: "Name", value: "String" } },
          },
        },
        {
          kind: "VariableDefinition",
          variable: { kind: "Variable", name: { kind: "Name", value: "rpcDurationMetric" } },
          type: {
            kind: "NonNullType",
            type: { kind: "NamedType", name: { kind: "Name", value: "String" } },
          },
        },
      ],
      selectionSet: {
        kind: "SelectionSet",
        selections: [
          {
            kind: "Field",
            alias: { kind: "Name", value: "red" },
            name: { kind: "Name", value: "serviceRed" },
            arguments: [
              {
                kind: "Argument",
                name: { kind: "Name", value: "service" },
                value: { kind: "Variable", name: { kind: "Name", value: "service" } },
              },
              {
                kind: "Argument",
                name: { kind: "Name", value: "fromNanos" },
                value: { kind: "Variable", name: { kind: "Name", value: "fromNanos" } },
              },
              {
                kind: "Argument",
                name: { kind: "Name", value: "toNanos" },
                value: { kind: "Variable", name: { kind: "Name", value: "toNanos" } },
              },
              {
                kind: "Argument",
                name: { kind: "Name", value: "stepSeconds" },
                value: { kind: "Variable", name: { kind: "Name", value: "stepSeconds" } },
              },
            ],
            selectionSet: {
              kind: "SelectionSet",
              selections: [
                {
                  kind: "Field",
                  name: { kind: "Name", value: "rate" },
                  selectionSet: {
                    kind: "SelectionSet",
                    selections: [
                      { kind: "Field", name: { kind: "Name", value: "tsNanos" } },
                      { kind: "Field", name: { kind: "Name", value: "value" } },
                    ],
                  },
                },
                {
                  kind: "Field",
                  name: { kind: "Name", value: "errorRate" },
                  selectionSet: {
                    kind: "SelectionSet",
                    selections: [
                      { kind: "Field", name: { kind: "Name", value: "tsNanos" } },
                      { kind: "Field", name: { kind: "Name", value: "value" } },
                    ],
                  },
                },
                {
                  kind: "Field",
                  name: { kind: "Name", value: "p50" },
                  selectionSet: {
                    kind: "SelectionSet",
                    selections: [
                      { kind: "Field", name: { kind: "Name", value: "tsNanos" } },
                      { kind: "Field", name: { kind: "Name", value: "value" } },
                    ],
                  },
                },
                {
                  kind: "Field",
                  name: { kind: "Name", value: "p95" },
                  selectionSet: {
                    kind: "SelectionSet",
                    selections: [
                      { kind: "Field", name: { kind: "Name", value: "tsNanos" } },
                      { kind: "Field", name: { kind: "Name", value: "value" } },
                    ],
                  },
                },
                {
                  kind: "Field",
                  name: { kind: "Name", value: "p99" },
                  selectionSet: {
                    kind: "SelectionSet",
                    selections: [
                      { kind: "Field", name: { kind: "Name", value: "tsNanos" } },
                      { kind: "Field", name: { kind: "Name", value: "value" } },
                    ],
                  },
                },
              ],
            },
          },
          {
            kind: "Field",
            alias: { kind: "Name", value: "overview" },
            name: { kind: "Name", value: "serviceOverview" },
            arguments: [
              {
                kind: "Argument",
                name: { kind: "Name", value: "service" },
                value: { kind: "Variable", name: { kind: "Name", value: "service" } },
              },
              {
                kind: "Argument",
                name: { kind: "Name", value: "fromNanos" },
                value: { kind: "Variable", name: { kind: "Name", value: "fromNanos" } },
              },
              {
                kind: "Argument",
                name: { kind: "Name", value: "toNanos" },
                value: { kind: "Variable", name: { kind: "Name", value: "toNanos" } },
              },
              {
                kind: "Argument",
                name: { kind: "Name", value: "stepSeconds" },
                value: { kind: "Variable", name: { kind: "Name", value: "stepSeconds" } },
              },
            ],
            selectionSet: {
              kind: "SelectionSet",
              selections: [
                {
                  kind: "Field",
                  name: { kind: "Name", value: "cpu" },
                  selectionSet: {
                    kind: "SelectionSet",
                    selections: [
                      { kind: "Field", name: { kind: "Name", value: "tsNanos" } },
                      { kind: "Field", name: { kind: "Name", value: "value" } },
                    ],
                  },
                },
                {
                  kind: "Field",
                  name: { kind: "Name", value: "memory" },
                  selectionSet: {
                    kind: "SelectionSet",
                    selections: [
                      { kind: "Field", name: { kind: "Name", value: "tsNanos" } },
                      { kind: "Field", name: { kind: "Name", value: "value" } },
                    ],
                  },
                },
                {
                  kind: "Field",
                  name: { kind: "Name", value: "requestRate" },
                  selectionSet: {
                    kind: "SelectionSet",
                    selections: [
                      { kind: "Field", name: { kind: "Name", value: "tsNanos" } },
                      { kind: "Field", name: { kind: "Name", value: "value" } },
                    ],
                  },
                },
                {
                  kind: "Field",
                  name: { kind: "Name", value: "errorRate" },
                  selectionSet: {
                    kind: "SelectionSet",
                    selections: [
                      { kind: "Field", name: { kind: "Name", value: "tsNanos" } },
                      { kind: "Field", name: { kind: "Name", value: "value" } },
                    ],
                  },
                },
                {
                  kind: "Field",
                  name: { kind: "Name", value: "latencyP50" },
                  selectionSet: {
                    kind: "SelectionSet",
                    selections: [
                      { kind: "Field", name: { kind: "Name", value: "tsNanos" } },
                      { kind: "Field", name: { kind: "Name", value: "value" } },
                    ],
                  },
                },
                {
                  kind: "Field",
                  name: { kind: "Name", value: "latencyP95" },
                  selectionSet: {
                    kind: "SelectionSet",
                    selections: [
                      { kind: "Field", name: { kind: "Name", value: "tsNanos" } },
                      { kind: "Field", name: { kind: "Name", value: "value" } },
                    ],
                  },
                },
                {
                  kind: "Field",
                  name: { kind: "Name", value: "latencyP99" },
                  selectionSet: {
                    kind: "SelectionSet",
                    selections: [
                      { kind: "Field", name: { kind: "Name", value: "tsNanos" } },
                      { kind: "Field", name: { kind: "Name", value: "value" } },
                    ],
                  },
                },
              ],
            },
          },
          {
            kind: "Field",
            name: { kind: "Name", value: "releases" },
            arguments: [
              {
                kind: "Argument",
                name: { kind: "Name", value: "service" },
                value: { kind: "Variable", name: { kind: "Name", value: "service" } },
              },
              {
                kind: "Argument",
                name: { kind: "Name", value: "fromNanos" },
                value: { kind: "Variable", name: { kind: "Name", value: "fromNanos" } },
              },
              {
                kind: "Argument",
                name: { kind: "Name", value: "toNanos" },
                value: { kind: "Variable", name: { kind: "Name", value: "toNanos" } },
              },
            ],
            selectionSet: {
              kind: "SelectionSet",
              selections: [
                { kind: "Field", name: { kind: "Name", value: "version" } },
                { kind: "Field", name: { kind: "Name", value: "firstSeenNanos" } },
                { kind: "Field", name: { kind: "Name", value: "lastSeenNanos" } },
                { kind: "Field", name: { kind: "Name", value: "spanCount" } },
              ],
            },
          },
          {
            kind: "Field",
            name: { kind: "Name", value: "serviceCatalog" },
            arguments: [
              {
                kind: "Argument",
                name: { kind: "Name", value: "fromNanos" },
                value: { kind: "Variable", name: { kind: "Name", value: "fromNanos" } },
              },
              {
                kind: "Argument",
                name: { kind: "Name", value: "toNanos" },
                value: { kind: "Variable", name: { kind: "Name", value: "toNanos" } },
              },
            ],
            selectionSet: {
              kind: "SelectionSet",
              selections: [
                { kind: "Field", name: { kind: "Name", value: "name" } },
                { kind: "Field", name: { kind: "Name", value: "serviceVersion" } },
                { kind: "Field", name: { kind: "Name", value: "serviceNamespace" } },
                { kind: "Field", name: { kind: "Name", value: "deploymentEnvironment" } },
                { kind: "Field", name: { kind: "Name", value: "telemetrySdkLanguage" } },
                { kind: "Field", name: { kind: "Name", value: "telemetrySdkName" } },
                { kind: "Field", name: { kind: "Name", value: "telemetrySdkVersion" } },
                { kind: "Field", name: { kind: "Name", value: "lastSeenNanos" } },
                { kind: "Field", name: { kind: "Name", value: "instanceCount" } },
              ],
            },
          },
          {
            kind: "Field",
            alias: { kind: "Name", value: "httpDurationExemplars" },
            name: { kind: "Name", value: "metricExemplars" },
            arguments: [
              {
                kind: "Argument",
                name: { kind: "Name", value: "name" },
                value: { kind: "Variable", name: { kind: "Name", value: "httpDurationMetric" } },
              },
              {
                kind: "Argument",
                name: { kind: "Name", value: "service" },
                value: { kind: "Variable", name: { kind: "Name", value: "service" } },
              },
              {
                kind: "Argument",
                name: { kind: "Name", value: "fromNanos" },
                value: { kind: "Variable", name: { kind: "Name", value: "fromNanos" } },
              },
              {
                kind: "Argument",
                name: { kind: "Name", value: "toNanos" },
                value: { kind: "Variable", name: { kind: "Name", value: "toNanos" } },
              },
              {
                kind: "Argument",
                name: { kind: "Name", value: "limit" },
                value: { kind: "IntValue", value: "50" },
              },
            ],
            selectionSet: {
              kind: "SelectionSet",
              selections: [
                { kind: "Field", name: { kind: "Name", value: "tsNanos" } },
                { kind: "Field", name: { kind: "Name", value: "service" } },
                { kind: "Field", name: { kind: "Name", value: "name" } },
                { kind: "Field", name: { kind: "Name", value: "value" } },
                { kind: "Field", name: { kind: "Name", value: "traceId" } },
                { kind: "Field", name: { kind: "Name", value: "spanId" } },
                { kind: "Field", name: { kind: "Name", value: "invocationId" } },
                { kind: "Field", name: { kind: "Name", value: "attributes" } },
              ],
            },
          },
          {
            kind: "Field",
            alias: { kind: "Name", value: "rpcDurationExemplars" },
            name: { kind: "Name", value: "metricExemplars" },
            arguments: [
              {
                kind: "Argument",
                name: { kind: "Name", value: "name" },
                value: { kind: "Variable", name: { kind: "Name", value: "rpcDurationMetric" } },
              },
              {
                kind: "Argument",
                name: { kind: "Name", value: "service" },
                value: { kind: "Variable", name: { kind: "Name", value: "service" } },
              },
              {
                kind: "Argument",
                name: { kind: "Name", value: "fromNanos" },
                value: { kind: "Variable", name: { kind: "Name", value: "fromNanos" } },
              },
              {
                kind: "Argument",
                name: { kind: "Name", value: "toNanos" },
                value: { kind: "Variable", name: { kind: "Name", value: "toNanos" } },
              },
              {
                kind: "Argument",
                name: { kind: "Name", value: "limit" },
                value: { kind: "IntValue", value: "50" },
              },
            ],
            selectionSet: {
              kind: "SelectionSet",
              selections: [
                { kind: "Field", name: { kind: "Name", value: "tsNanos" } },
                { kind: "Field", name: { kind: "Name", value: "service" } },
                { kind: "Field", name: { kind: "Name", value: "name" } },
                { kind: "Field", name: { kind: "Name", value: "value" } },
                { kind: "Field", name: { kind: "Name", value: "traceId" } },
                { kind: "Field", name: { kind: "Name", value: "spanId" } },
                { kind: "Field", name: { kind: "Name", value: "invocationId" } },
                { kind: "Field", name: { kind: "Name", value: "attributes" } },
              ],
            },
          },
          {
            kind: "Field",
            name: { kind: "Name", value: "runtimeSnapshot" },
            arguments: [
              {
                kind: "Argument",
                name: { kind: "Name", value: "service" },
                value: { kind: "Variable", name: { kind: "Name", value: "service" } },
              },
              {
                kind: "Argument",
                name: { kind: "Name", value: "fromNanos" },
                value: { kind: "Variable", name: { kind: "Name", value: "fromNanos" } },
              },
              {
                kind: "Argument",
                name: { kind: "Name", value: "toNanos" },
                value: { kind: "Variable", name: { kind: "Name", value: "toNanos" } },
              },
              {
                kind: "Argument",
                name: { kind: "Name", value: "stepSeconds" },
                value: { kind: "Variable", name: { kind: "Name", value: "stepSeconds" } },
              },
            ],
            selectionSet: {
              kind: "SelectionSet",
              selections: [
                { kind: "Field", name: { kind: "Name", value: "family" } },
                { kind: "Field", name: { kind: "Name", value: "metric" } },
                { kind: "Field", name: { kind: "Name", value: "unit" } },
                {
                  kind: "Field",
                  name: { kind: "Name", value: "points" },
                  selectionSet: {
                    kind: "SelectionSet",
                    selections: [
                      { kind: "Field", name: { kind: "Name", value: "tsNanos" } },
                      { kind: "Field", name: { kind: "Name", value: "value" } },
                    ],
                  },
                },
              ],
            },
          },
          {
            kind: "Field",
            name: { kind: "Name", value: "tracesPage" },
            arguments: [
              {
                kind: "Argument",
                name: { kind: "Name", value: "service" },
                value: { kind: "Variable", name: { kind: "Name", value: "service" } },
              },
              {
                kind: "Argument",
                name: { kind: "Name", value: "sort" },
                value: { kind: "EnumValue", value: "START_DESC" },
              },
              {
                kind: "Argument",
                name: { kind: "Name", value: "limit" },
                value: { kind: "IntValue", value: "10" },
              },
              {
                kind: "Argument",
                name: { kind: "Name", value: "fromNanos" },
                value: { kind: "Variable", name: { kind: "Name", value: "fromNanos" } },
              },
              {
                kind: "Argument",
                name: { kind: "Name", value: "toNanos" },
                value: { kind: "Variable", name: { kind: "Name", value: "toNanos" } },
              },
            ],
            selectionSet: {
              kind: "SelectionSet",
              selections: [
                {
                  kind: "Field",
                  name: { kind: "Name", value: "items" },
                  selectionSet: {
                    kind: "SelectionSet",
                    selections: [
                      { kind: "Field", name: { kind: "Name", value: "traceId" } },
                      { kind: "Field", name: { kind: "Name", value: "rootName" } },
                      { kind: "Field", name: { kind: "Name", value: "service" } },
                      { kind: "Field", name: { kind: "Name", value: "startNanos" } },
                      { kind: "Field", name: { kind: "Name", value: "durationNs" } },
                      { kind: "Field", name: { kind: "Name", value: "spanCount" } },
                      { kind: "Field", name: { kind: "Name", value: "hasError" } },
                    ],
                  },
                },
              ],
            },
          },
        ],
      },
    },
  ],
} as unknown as DocumentNode<ServiceDetailQuery, ServiceDetailQueryVariables>

type Properties<T> = {
  [K in keyof T]: z.ZodType<T[K], T[K] | undefined>
}

type definedNonNullAny = {}

export const isDefinedNonNullAny = (v: any): v is definedNonNullAny => v !== undefined && v !== null

export const definedNonNullAnySchema = z.any().refine((v) => isDefinedNonNullAny(v))

export const TraceSortSchema: z.ZodType<
  "DURATION_ASC" | "DURATION_DESC" | "SPAN_COUNT_DESC" | "START_DESC",
  "DURATION_ASC" | "DURATION_DESC" | "SPAN_COUNT_DESC" | "START_DESC"
> = z.enum(["DURATION_ASC", "DURATION_DESC", "SPAN_COUNT_DESC", "START_DESC"])

export const TestResultStatusSchema: z.ZodType<
  "BROKEN" | "FAILED" | "PASSED" | "SKIPPED" | "UNKNOWN",
  "BROKEN" | "FAILED" | "PASSED" | "SKIPPED" | "UNKNOWN"
> = z.enum(["BROKEN", "FAILED", "PASSED", "SKIPPED", "UNKNOWN"])

export const TestFlakyStateSchema: z.ZodType<
  "BROKEN" | "FIXED" | "FLAKY" | "HEALTHY",
  "BROKEN" | "FIXED" | "FLAKY" | "HEALTHY"
> = z.enum(["BROKEN", "FIXED", "FLAKY", "HEALTHY"])

export const TestExplorerSortSchema: z.ZodType<"LAST_SEEN" | "NAME", "LAST_SEEN" | "NAME"> = z.enum(
  ["LAST_SEEN", "NAME"]
)

export const TestRollupSchema: z.ZodType<
  "BROKEN" | "FAILED" | "FLAKY_PASS" | "PASSED" | "SKIPPED" | "UNKNOWN",
  "BROKEN" | "FAILED" | "FLAKY_PASS" | "PASSED" | "SKIPPED" | "UNKNOWN"
> = z.enum(["BROKEN", "FAILED", "FLAKY_PASS", "PASSED", "SKIPPED", "UNKNOWN"])

export const TestIdentitySourceSchema: z.ZodType<
  "CODE_REFERENCE" | "EXPLICIT" | "NAME_PATH",
  "CODE_REFERENCE" | "EXPLICIT" | "NAME_PATH"
> = z.enum(["CODE_REFERENCE", "EXPLICIT", "NAME_PATH"])

export const SignalKindSchema: z.ZodType<
  "ERRORS" | "LOGS" | "METRIC_POINTS" | "SPANS" | "TRACES",
  "ERRORS" | "LOGS" | "METRIC_POINTS" | "SPANS" | "TRACES"
> = z.enum(["ERRORS", "LOGS", "METRIC_POINTS", "SPANS", "TRACES"])

export const IssueSortSchema: z.ZodType<
  "EVENTS" | "FIRST_SEEN" | "LAST_SEEN" | "TREND",
  "EVENTS" | "FIRST_SEEN" | "LAST_SEEN" | "TREND"
> = z.enum(["EVENTS", "FIRST_SEEN", "LAST_SEEN", "TREND"])

export const TestConfigurationFilterInputSchema: z.ZodObject<
  Properties<TestConfigurationFilterInput>
> = z.object({
  key: z.string(),
  value: z.string(),
})

export const AttributeFilterInputSchema: z.ZodObject<Properties<AttributeFilterInput>> = z.object({
  key: z.string(),
  op: z.string(),
  value: z.string(),
})

export const AlertRuleInputSchema: z.ZodObject<Properties<AlertRuleInput>> = z.object({
  attributeFilters: z.string().nullable(),
  comparator: z.string(),
  consecutiveBreachesRequired: z.number().nullable(),
  consecutiveHealthyRequired: z.number().nullable(),
  destinationIds: z.array(z.string()).nullable(),
  enabled: z.boolean().nullable(),
  excludeServices: z.array(z.string()).nullable(),
  groupBy: z.string().nullable(),
  id: z.string().nullable(),
  metricAggregation: z.string().nullable(),
  metricName: z.string().nullable(),
  minimumSampleCount: z.number().nullable(),
  name: z.string(),
  noDataBehavior: z.string().nullable(),
  renotifyIntervalMinutes: z.number().nullable(),
  services: z.array(z.string()).nullable(),
  severity: z.string(),
  signalType: z.string(),
  threshold: z.number(),
  thresholdUpper: z.number().nullable(),
  windowMinutes: z.number(),
})

export const ServiceDetailQuerySchema: z.ZodType<ServiceDetailQuery> = z.object({
  red: z.object({
    rate: z.array(
      z.object({
        tsNanos: z.string(),
        value: z.number(),
      })
    ),
    errorRate: z.array(
      z.object({
        tsNanos: z.string(),
        value: z.number(),
      })
    ),
    p50: z.array(
      z.object({
        tsNanos: z.string(),
        value: z.number(),
      })
    ),
    p95: z.array(
      z.object({
        tsNanos: z.string(),
        value: z.number(),
      })
    ),
    p99: z.array(
      z.object({
        tsNanos: z.string(),
        value: z.number(),
      })
    ),
  }),
  overview: z.object({
    cpu: z.array(
      z.object({
        tsNanos: z.string(),
        value: z.number(),
      })
    ),
    memory: z.array(
      z.object({
        tsNanos: z.string(),
        value: z.number(),
      })
    ),
    requestRate: z.array(
      z.object({
        tsNanos: z.string(),
        value: z.number(),
      })
    ),
    errorRate: z.array(
      z.object({
        tsNanos: z.string(),
        value: z.number(),
      })
    ),
    latencyP50: z.array(
      z.object({
        tsNanos: z.string(),
        value: z.number(),
      })
    ),
    latencyP95: z.array(
      z.object({
        tsNanos: z.string(),
        value: z.number(),
      })
    ),
    latencyP99: z.array(
      z.object({
        tsNanos: z.string(),
        value: z.number(),
      })
    ),
  }),
  releases: z.array(
    z.object({
      version: z.string(),
      firstSeenNanos: z.string(),
      lastSeenNanos: z.string(),
      spanCount: z.string(),
    })
  ),
  serviceCatalog: z.array(
    z.object({
      name: z.string(),
      serviceVersion: z.string().nullable(),
      serviceNamespace: z.string().nullable(),
      deploymentEnvironment: z.string().nullable(),
      telemetrySdkLanguage: z.string().nullable(),
      telemetrySdkName: z.string().nullable(),
      telemetrySdkVersion: z.string().nullable(),
      lastSeenNanos: z.string(),
      instanceCount: z.string(),
    })
  ),
  httpDurationExemplars: z.array(
    z.object({
      tsNanos: z.string(),
      service: z.string(),
      name: z.string(),
      value: z.number(),
      traceId: z.string(),
      spanId: z.string(),
      invocationId: z.string().nullable(),
      attributes: z.string(),
    })
  ),
  rpcDurationExemplars: z.array(
    z.object({
      tsNanos: z.string(),
      service: z.string(),
      name: z.string(),
      value: z.number(),
      traceId: z.string(),
      spanId: z.string(),
      invocationId: z.string().nullable(),
      attributes: z.string(),
    })
  ),
  runtimeSnapshot: z.array(
    z.object({
      family: z.string(),
      metric: z.string(),
      unit: z.string().nullable(),
      points: z.array(
        z.object({
          tsNanos: z.string(),
          value: z.number(),
        })
      ),
    })
  ),
  tracesPage: z.object({
    items: z.array(
      z.object({
        traceId: z.string(),
        rootName: z.string(),
        service: z.string(),
        startNanos: z.string(),
        durationNs: z.string(),
        spanCount: z.number(),
        hasError: z.boolean(),
      })
    ),
  }),
})
