/* AUTO-GENERATED by GraphQL Code Generator — DO NOT EDIT. Plan 152. */
// @ts-nocheck

/** Internal type. DO NOT USE DIRECTLY. */
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] }
/** Internal type. DO NOT USE DIRECTLY. */
export type Incremental<T> =
  | T
  | { [P in keyof T]?: P extends " $fragmentName" | "__typename" ? T[P] : never }
import type * as Types from "../../../platform/graphql/generated/schema-types.generated"

import * as z from "zod"
import type {
  TraceSort,
  TestResultStatus,
  TestFlakyState,
  TestExplorerSort,
  TestRollup,
  TestConfigurationFilterInput,
  TestIdentitySource,
  SignalKind,
  IssueSort,
  AttributeFilterInput,
  AlertRuleInput,
  RumTraceQuery,
} from "@/platform/graphql/generated/schema-types.generated"
import type { TypedDocumentNode as DocumentNode } from "@/platform/graphql/typed-document"
export type RumTraceQueryVariables = Exact<{
  traceId: string
}>

export type RumTraceQuery = {
  readonly linkedTraces: ReadonlyArray<{
    readonly traceId: string
    readonly rootName: string
    readonly service: string
    readonly startNanos: string
    readonly durationNs: string
    readonly spanCount: number
    readonly hasError: boolean
  }>
  readonly logsByTrace: ReadonlyArray<{
    readonly tsNanos: string
    readonly severityText: string
    readonly body: string
    readonly service: string
    readonly spanId: string
  }>
}

export const RumTraceDocument = {
  kind: "Document",
  definitions: [
    {
      kind: "OperationDefinition",
      operation: "query",
      name: { kind: "Name", value: "RumTrace" },
      variableDefinitions: [
        {
          kind: "VariableDefinition",
          variable: { kind: "Variable", name: { kind: "Name", value: "traceId" } },
          type: {
            kind: "NonNullType",
            type: { kind: "NamedType", name: { kind: "Name", value: "String" } },
          },
        },
      ],
      selectionSet: {
        kind: "SelectionSet",
        selections: [
          {
            kind: "Field",
            name: { kind: "Name", value: "linkedTraces" },
            arguments: [
              {
                kind: "Argument",
                name: { kind: "Name", value: "traceId" },
                value: { kind: "Variable", name: { kind: "Name", value: "traceId" } },
              },
            ],
            selectionSet: {
              kind: "SelectionSet",
              selections: [
                { kind: "Field", name: { kind: "Name", value: "traceId" } },
                { kind: "Field", name: { kind: "Name", value: "rootName" } },
                { kind: "Field", name: { kind: "Name", value: "service" } },
                { kind: "Field", name: { kind: "Name", value: "startNanos" } },
                { kind: "Field", name: { kind: "Name", value: "durationNs" } },
                { kind: "Field", name: { kind: "Name", value: "spanCount" } },
                { kind: "Field", name: { kind: "Name", value: "hasError" } },
              ],
            },
          },
          {
            kind: "Field",
            name: { kind: "Name", value: "logsByTrace" },
            arguments: [
              {
                kind: "Argument",
                name: { kind: "Name", value: "traceId" },
                value: { kind: "Variable", name: { kind: "Name", value: "traceId" } },
              },
            ],
            selectionSet: {
              kind: "SelectionSet",
              selections: [
                { kind: "Field", name: { kind: "Name", value: "tsNanos" } },
                { kind: "Field", name: { kind: "Name", value: "severityText" } },
                { kind: "Field", name: { kind: "Name", value: "body" } },
                { kind: "Field", name: { kind: "Name", value: "service" } },
                { kind: "Field", name: { kind: "Name", value: "spanId" } },
              ],
            },
          },
        ],
      },
    },
  ],
} as unknown as DocumentNode<RumTraceQuery, RumTraceQueryVariables>

type Properties<T> = {
  [K in keyof T]: z.ZodType<T[K], T[K] | undefined>
}

type definedNonNullAny = {}

export const isDefinedNonNullAny = (v: any): v is definedNonNullAny => v !== undefined && v !== null

export const definedNonNullAnySchema = z.any().refine((v) => isDefinedNonNullAny(v))

export const TraceSortSchema: z.ZodType<
  "DURATION_ASC" | "DURATION_DESC" | "SPAN_COUNT_DESC" | "START_DESC",
  "DURATION_ASC" | "DURATION_DESC" | "SPAN_COUNT_DESC" | "START_DESC"
> = z.enum(["DURATION_ASC", "DURATION_DESC", "SPAN_COUNT_DESC", "START_DESC"])

export const TestResultStatusSchema: z.ZodType<
  "BROKEN" | "FAILED" | "PASSED" | "SKIPPED" | "UNKNOWN",
  "BROKEN" | "FAILED" | "PASSED" | "SKIPPED" | "UNKNOWN"
> = z.enum(["BROKEN", "FAILED", "PASSED", "SKIPPED", "UNKNOWN"])

export const TestFlakyStateSchema: z.ZodType<
  "BROKEN" | "FIXED" | "FLAKY" | "HEALTHY",
  "BROKEN" | "FIXED" | "FLAKY" | "HEALTHY"
> = z.enum(["BROKEN", "FIXED", "FLAKY", "HEALTHY"])

export const TestExplorerSortSchema: z.ZodType<"LAST_SEEN" | "NAME", "LAST_SEEN" | "NAME"> = z.enum(
  ["LAST_SEEN", "NAME"]
)

export const TestRollupSchema: z.ZodType<
  "BROKEN" | "FAILED" | "FLAKY_PASS" | "PASSED" | "SKIPPED" | "UNKNOWN",
  "BROKEN" | "FAILED" | "FLAKY_PASS" | "PASSED" | "SKIPPED" | "UNKNOWN"
> = z.enum(["BROKEN", "FAILED", "FLAKY_PASS", "PASSED", "SKIPPED", "UNKNOWN"])

export const TestIdentitySourceSchema: z.ZodType<
  "CODE_REFERENCE" | "EXPLICIT" | "NAME_PATH",
  "CODE_REFERENCE" | "EXPLICIT" | "NAME_PATH"
> = z.enum(["CODE_REFERENCE", "EXPLICIT", "NAME_PATH"])

export const SignalKindSchema: z.ZodType<
  "ERRORS" | "LOGS" | "METRIC_POINTS" | "SPANS" | "TRACES",
  "ERRORS" | "LOGS" | "METRIC_POINTS" | "SPANS" | "TRACES"
> = z.enum(["ERRORS", "LOGS", "METRIC_POINTS", "SPANS", "TRACES"])

export const IssueSortSchema: z.ZodType<
  "EVENTS" | "FIRST_SEEN" | "LAST_SEEN" | "TREND",
  "EVENTS" | "FIRST_SEEN" | "LAST_SEEN" | "TREND"
> = z.enum(["EVENTS", "FIRST_SEEN", "LAST_SEEN", "TREND"])

export const TestConfigurationFilterInputSchema: z.ZodObject<
  Properties<TestConfigurationFilterInput>
> = z.object({
  key: z.string(),
  value: z.string(),
})

export const AttributeFilterInputSchema: z.ZodObject<Properties<AttributeFilterInput>> = z.object({
  key: z.string(),
  op: z.string(),
  value: z.string(),
})

export const AlertRuleInputSchema: z.ZodObject<Properties<AlertRuleInput>> = z.object({
  attributeFilters: z.string().nullable(),
  comparator: z.string(),
  consecutiveBreachesRequired: z.number().nullable(),
  consecutiveHealthyRequired: z.number().nullable(),
  destinationIds: z.array(z.string()).nullable(),
  enabled: z.boolean().nullable(),
  excludeServices: z.array(z.string()).nullable(),
  groupBy: z.string().nullable(),
  id: z.string().nullable(),
  metricAggregation: z.string().nullable(),
  metricName: z.string().nullable(),
  minimumSampleCount: z.number().nullable(),
  name: z.string(),
  noDataBehavior: z.string().nullable(),
  renotifyIntervalMinutes: z.number().nullable(),
  services: z.array(z.string()).nullable(),
  severity: z.string(),
  signalType: z.string(),
  threshold: z.number(),
  thresholdUpper: z.number().nullable(),
  windowMinutes: z.number(),
})

export const RumTraceQuerySchema: z.ZodType<RumTraceQuery> = z.object({
  linkedTraces: z.array(
    z.object({
      traceId: z.string(),
      rootName: z.string(),
      service: z.string(),
      startNanos: z.string(),
      durationNs: z.string(),
      spanCount: z.number(),
      hasError: z.boolean(),
    })
  ),
  logsByTrace: z.array(
    z.object({
      tsNanos: z.string(),
      severityText: z.string(),
      body: z.string(),
      service: z.string(),
      spanId: z.string(),
    })
  ),
})
