[package]
name = "parallax-api"
description = "Parallax GraphQL API schema"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
parallax-analysis = { workspace = true }
tokio = { workspace = true }
juniper = { workspace = true, features = ["schema-language"] }
parallax-evidence = { workspace = true }
parallax-storage = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
parallax-metadata = { workspace = true }
parallax-test-support = { workspace = true }
