[package]
name = "parallax-greptime"
description = "Parallax GreptimeDB native-table telemetry adapter"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
arrow = { workspace = true }
arrow-ipc = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
futures-util = { workspace = true }
parallax-model = { workspace = true }
parallax-proto = { workspace = true }
parallax-semconv = { workspace = true }
parallax-storage = { workspace = true }
reqwest = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[features]
cross-release-vendored = ["reqwest/native-tls-vendored"]
