query IssueOccurrences(
  $service: String!
  $fingerprint: String!
  $fromNanos: String!
  $toNanos: String!
) {
  issue(service: $service, fingerprint: $fingerprint) {
    events(limit: 50, fromNanos: $fromNanos, toNanos: $toNanos) {
      tsNanos
      service
      serviceVersion
      message
      stacktrace
      source
      traceId
      spanId
      attributes
      mappedFrames {
        raw
        file
        line
        column
        resolved
        source
        sourceLine
        sourceColumn
        name
      }
    }
  }
}
