/* AUTO-GENERATED by GraphQL Code Generator — DO NOT EDIT. Plan 152. */
// @ts-nocheck

/** Internal type. DO NOT USE DIRECTLY. */
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] }
/** Internal type. DO NOT USE DIRECTLY. */
export type Incremental<T> =
  | T
  | {
      [P in keyof T]?: P extends " $fragmentName" | "__typename" ? T[P] : never
    }
import type * as Types from "../../../platform/graphql/generated/schema-types.generated"

import * as z from "zod"
import type {
  TraceSort,
  SignalKind,
  IssueSort,
  AttributeFilterInput,
  AlertRuleInput,
  IssueSetStatusMutation,
} from "@/platform/graphql/generated/schema-types.generated"
import type { TypedDocumentNode as DocumentNode } from "@/platform/graphql/typed-document"
export type IssueSetStatusMutationVariables = Exact<{
  fingerprint: string
  status: string
}>

export type IssueSetStatusMutation = {
  readonly issueSetStatus: { readonly status: string }
}

export const IssueSetStatusDocument = {
  kind: "Document",
  definitions: [
    {
      kind: "OperationDefinition",
      operation: "mutation",
      name: { kind: "Name", value: "IssueSetStatus" },
      variableDefinitions: [
        {
          kind: "VariableDefinition",
          variable: {
            kind: "Variable",
            name: { kind: "Name", value: "fingerprint" },
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: { kind: "Name", value: "String" },
            },
          },
        },
        {
          kind: "VariableDefinition",
          variable: {
            kind: "Variable",
            name: { kind: "Name", value: "status" },
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: { kind: "Name", value: "String" },
            },
          },
        },
      ],
      selectionSet: {
        kind: "SelectionSet",
        selections: [
          {
            kind: "Field",
            name: { kind: "Name", value: "issueSetStatus" },
            arguments: [
              {
                kind: "Argument",
                name: { kind: "Name", value: "fingerprint" },
                value: {
                  kind: "Variable",
                  name: { kind: "Name", value: "fingerprint" },
                },
              },
              {
                kind: "Argument",
                name: { kind: "Name", value: "status" },
                value: {
                  kind: "Variable",
                  name: { kind: "Name", value: "status" },
                },
              },
            ],
            selectionSet: {
              kind: "SelectionSet",
              selections: [{ kind: "Field", name: { kind: "Name", value: "status" } }],
            },
          },
        ],
      },
    },
  ],
} as unknown as DocumentNode<IssueSetStatusMutation, IssueSetStatusMutationVariables>

type Properties<T> = {
  [K in keyof T]: z.ZodType<T[K], T[K] | undefined>
}

type definedNonNullAny = {}

export const isDefinedNonNullAny = (v: any): v is definedNonNullAny => v !== undefined && v !== null

export const definedNonNullAnySchema = z.any().refine((v) => isDefinedNonNullAny(v))

export const TraceSortSchema: z.ZodType<
  "DURATION_ASC" | "DURATION_DESC" | "SPAN_COUNT_DESC" | "START_DESC",
  "DURATION_ASC" | "DURATION_DESC" | "SPAN_COUNT_DESC" | "START_DESC"
> = z.enum(["DURATION_ASC", "DURATION_DESC", "SPAN_COUNT_DESC", "START_DESC"])

export const SignalKindSchema: z.ZodType<
  "ERRORS" | "LOGS" | "METRIC_POINTS" | "SPANS" | "TRACES",
  "ERRORS" | "LOGS" | "METRIC_POINTS" | "SPANS" | "TRACES"
> = z.enum(["ERRORS", "LOGS", "METRIC_POINTS", "SPANS", "TRACES"])

export const IssueSortSchema: z.ZodType<
  "EVENTS" | "FIRST_SEEN" | "LAST_SEEN" | "TREND",
  "EVENTS" | "FIRST_SEEN" | "LAST_SEEN" | "TREND"
> = z.enum(["EVENTS", "FIRST_SEEN", "LAST_SEEN", "TREND"])

export const AttributeFilterInputSchema: z.ZodObject<Properties<AttributeFilterInput>> = z.object({
  key: z.string(),
  op: z.string(),
  value: z.string(),
})

export const AlertRuleInputSchema: z.ZodObject<Properties<AlertRuleInput>> = z.object({
  attributeFilters: z.string().nullable(),
  comparator: z.string(),
  consecutiveBreachesRequired: z.number().nullable(),
  consecutiveHealthyRequired: z.number().nullable(),
  destinationIds: z.array(z.string()).nullable(),
  enabled: z.boolean().nullable(),
  excludeServices: z.array(z.string()).nullable(),
  groupBy: z.string().nullable(),
  id: z.string().nullable(),
  metricAggregation: z.string().nullable(),
  metricName: z.string().nullable(),
  minimumSampleCount: z.number().nullable(),
  name: z.string(),
  noDataBehavior: z.string().nullable(),
  renotifyIntervalMinutes: z.number().nullable(),
  services: z.array(z.string()).nullable(),
  severity: z.string(),
  signalType: z.string(),
  threshold: z.number(),
  thresholdUpper: z.number().nullable(),
  windowMinutes: z.number(),
})

export const IssueSetStatusMutationSchema: z.ZodType<IssueSetStatusMutation> = z.object({
  issueSetStatus: z.object({
    status: z.string(),
  }),
})
