// Plan 152 — exact Bun GraphQL Code Generator config.
// Plan 149 — first feature operation: Zod importFrom uses the absolute @/
// alias so fixture depth and features/<f>/api depth both resolve.
// Invoke only: bunx --bun --no-install graphql-codegen --config codegen.ts
// Do not edit generated outputs; re-run the generator.

import type { CodegenConfig } from "@graphql-codegen/cli"

const sharedConfig = {
  strictScalars: true,
  scalars: {
    // Juniper SDL uses built-in GraphQL scalars only today.
    ID: { input: "string", output: "string" },
    String: { input: "string", output: "string" },
    Boolean: { input: "boolean", output: "boolean" },
    Int: { input: "number", output: "number" },
    Float: { input: "number", output: "number" },
  },
  avoidOptionals: {
    field: true,
    object: true,
    inputValue: false,
    defaultValue: false,
  },
  maybeValue: "T | null",
  inputMaybeValue: "T | null | undefined",
  documentMode: "documentNode" as const,
  immutableTypes: true,
  useTypeImports: true,
  enumsAsTypes: true,
  preResolveTypes: true,
  onlyOperationTypes: true,
}

const config: CodegenConfig = {
  schema: "./graphql/schema.graphql",
  // Production feature operations + one platform probe. No snapshots/build.
  documents: [
    "src/features/**/api/*.graphql",
    "src/platform/graphql/tests/fixtures/*.graphql",
  ],
  ignoreNoDocuments: true,
  generates: {
    "src/platform/graphql/generated/schema-types.generated.ts": {
      plugins: [
        {
          add: {
            content:
              "/* AUTO-GENERATED by GraphQL Code Generator — DO NOT EDIT. Plan 152. */\n// @ts-nocheck\n",
          },
        },
        "typescript",
      ],
      config: {
        ...sharedConfig,
        onlyOperationTypes: false,
      },
    },
    "src/": {
      preset: "near-operation-file",
      presetConfig: {
        extension: ".generated.ts",
        baseTypesPath: "platform/graphql/generated/schema-types.generated.ts",
        folder: "",
      },
      plugins: [
        {
          add: {
            content:
              "/* AUTO-GENERATED by GraphQL Code Generator — DO NOT EDIT. Plan 152. */\n// @ts-nocheck\n",
          },
        },
        "typescript-operations",
        "typed-document-node",
        {
          "typescript-validation-schema": {
            schema: "zodv4",
            withOperationType: true,
            withObjectType: false,
            zodOptionalType: "nullable",
            // Absolute alias works for both fixture and feature document depths.
            importFrom: "@/platform/graphql/generated/schema-types.generated",
            useTypeImports: true,
            validationSchemaExportType: "const",
          },
        },
      ],
      config: {
        ...sharedConfig,
        schema: "zodv4",
        withOperationType: true,
        withObjectType: false,
        zodOptionalType: "nullable",
        // Local TypedDocumentNode — Oxc cannot resolve the empty-main core pkg.
        documentNodeImport:
          "@/platform/graphql/typed-document#TypedDocumentNode",
      },
    },
  },
  hooks: {
    afterAllFileWrite: ["bun ./node_modules/oxfmt/bin/oxfmt --write"],
  },
}

export default config
