//  @ts-check

import { tanstackConfig } from "@tanstack/eslint-config"

export default [
  ...tanstackConfig,
  {
    rules: {
      "import/no-cycle": "off",
      "import/order": "off",
      "sort-imports": "off",
      "@typescript-eslint/array-type": "off",
      "@typescript-eslint/require-await": "off",
      "pnpm/json-enforce-catalog": "off",
    },
  },
  {
    // shadcn-generated primitives: regenerated by the shadcn CLI, kept
    // verbatim — relax the strict rules that fight its house style.
    files: ["src/components/ui/**"],
    rules: {
      "no-shadow": "off",
      "@typescript-eslint/no-unnecessary-condition": "off",
    },
  },
  {
    ignores: ["eslint.config.js", ".prettierrc"],
  },
]
