/* AUTO-GENERATED by GraphQL Code Generator — DO NOT EDIT. Plan 152. */
// @ts-nocheck

/** Internal type. DO NOT USE DIRECTLY. */
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] }
/** Internal type. DO NOT USE DIRECTLY. */
export type Incremental<T> =
  | T
  | { [P in keyof T]?: P extends " $fragmentName" | "__typename" ? T[P] : never }
import type * as Types from "../../generated/schema-types.generated"

import * as z from "zod"
import type {
  TraceSort,
  TestResultStatus,
  TestFlakyState,
  TestExplorerSort,
  TestRollup,
  TestConfigurationFilterInput,
  TestIdentitySource,
  SignalKind,
  IssueSort,
  AttributeFilterInput,
  AlertRuleInput,
  GraphqlContractStaticProbeQuery,
} from "@/platform/graphql/generated/schema-types.generated"
import type { TypedDocumentNode as DocumentNode } from "@/platform/graphql/typed-document"
export type GraphqlContractStaticProbeQueryVariables = Exact<{
  fromNanos: string
  toNanos: string
  fingerprint: string
  service?: string | null | undefined
  limit?: number | null | undefined
}>

export type GraphqlContractStaticProbeQuery = {
  readonly health: string
  readonly version: string
  readonly otlpGrpcPort: number
  readonly otlpHttpPort: number
  readonly metricNames: ReadonlyArray<string>
  readonly overview: {
    readonly spanCount: string
    readonly errorRate: number
    readonly activeServices: number
  }
  readonly issue: {
    readonly fingerprint: string
    readonly title: string
    readonly eventCount: number
  } | null
  readonly signalCountSeries: ReadonlyArray<{ readonly tsNanos: string; readonly value: number }>
}

export const GraphqlContractStaticProbeDocument = {
  kind: "Document",
  definitions: [
    {
      kind: "OperationDefinition",
      operation: "query",
      name: { kind: "Name", value: "GraphqlContractStaticProbe" },
      variableDefinitions: [
        {
          kind: "VariableDefinition",
          variable: { kind: "Variable", name: { kind: "Name", value: "fromNanos" } },
          type: {
            kind: "NonNullType",
            type: { kind: "NamedType", name: { kind: "Name", value: "String" } },
          },
        },
        {
          kind: "VariableDefinition",
          variable: { kind: "Variable", name: { kind: "Name", value: "toNanos" } },
          type: {
            kind: "NonNullType",
            type: { kind: "NamedType", name: { kind: "Name", value: "String" } },
          },
        },
        {
          kind: "VariableDefinition",
          variable: { kind: "Variable", name: { kind: "Name", value: "fingerprint" } },
          type: {
            kind: "NonNullType",
            type: { kind: "NamedType", name: { kind: "Name", value: "String" } },
          },
        },
        {
          kind: "VariableDefinition",
          variable: { kind: "Variable", name: { kind: "Name", value: "service" } },
          type: { kind: "NamedType", name: { kind: "Name", value: "String" } },
        },
        {
          kind: "VariableDefinition",
          variable: { kind: "Variable", name: { kind: "Name", value: "limit" } },
          type: { kind: "NamedType", name: { kind: "Name", value: "Int" } },
        },
      ],
      selectionSet: {
        kind: "SelectionSet",
        selections: [
          { kind: "Field", name: { kind: "Name", value: "health" } },
          { kind: "Field", name: { kind: "Name", value: "version" } },
          { kind: "Field", name: { kind: "Name", value: "otlpGrpcPort" } },
          { kind: "Field", name: { kind: "Name", value: "otlpHttpPort" } },
          {
            kind: "Field",
            name: { kind: "Name", value: "overview" },
            arguments: [
              {
                kind: "Argument",
                name: { kind: "Name", value: "fromNanos" },
                value: { kind: "Variable", name: { kind: "Name", value: "fromNanos" } },
              },
              {
                kind: "Argument",
                name: { kind: "Name", value: "toNanos" },
                value: { kind: "Variable", name: { kind: "Name", value: "toNanos" } },
              },
            ],
            selectionSet: {
              kind: "SelectionSet",
              selections: [
                { kind: "Field", name: { kind: "Name", value: "spanCount" } },
                { kind: "Field", name: { kind: "Name", value: "errorRate" } },
                { kind: "Field", name: { kind: "Name", value: "activeServices" } },
              ],
            },
          },
          {
            kind: "Field",
            name: { kind: "Name", value: "issue" },
            arguments: [
              {
                kind: "Argument",
                name: { kind: "Name", value: "fingerprint" },
                value: { kind: "Variable", name: { kind: "Name", value: "fingerprint" } },
              },
            ],
            selectionSet: {
              kind: "SelectionSet",
              selections: [
                { kind: "Field", name: { kind: "Name", value: "fingerprint" } },
                { kind: "Field", name: { kind: "Name", value: "title" } },
                { kind: "Field", name: { kind: "Name", value: "eventCount" } },
              ],
            },
          },
          {
            kind: "Field",
            name: { kind: "Name", value: "metricNames" },
            arguments: [
              {
                kind: "Argument",
                name: { kind: "Name", value: "prefix" },
                value: { kind: "Variable", name: { kind: "Name", value: "service" } },
              },
            ],
          },
          {
            kind: "Field",
            name: { kind: "Name", value: "signalCountSeries" },
            arguments: [
              {
                kind: "Argument",
                name: { kind: "Name", value: "kind" },
                value: { kind: "EnumValue", value: "LOGS" },
              },
              {
                kind: "Argument",
                name: { kind: "Name", value: "service" },
                value: { kind: "Variable", name: { kind: "Name", value: "service" } },
              },
              {
                kind: "Argument",
                name: { kind: "Name", value: "fromNanos" },
                value: { kind: "Variable", name: { kind: "Name", value: "fromNanos" } },
              },
              {
                kind: "Argument",
                name: { kind: "Name", value: "toNanos" },
                value: { kind: "Variable", name: { kind: "Name", value: "toNanos" } },
              },
              {
                kind: "Argument",
                name: { kind: "Name", value: "stepSeconds" },
                value: { kind: "Variable", name: { kind: "Name", value: "limit" } },
              },
            ],
            selectionSet: {
              kind: "SelectionSet",
              selections: [
                { kind: "Field", name: { kind: "Name", value: "tsNanos" } },
                { kind: "Field", name: { kind: "Name", value: "value" } },
              ],
            },
          },
        ],
      },
    },
  ],
} as unknown as DocumentNode<
  GraphqlContractStaticProbeQuery,
  GraphqlContractStaticProbeQueryVariables
>

type Properties<T> = {
  [K in keyof T]: z.ZodType<T[K], T[K] | undefined>
}

type definedNonNullAny = {}

export const isDefinedNonNullAny = (v: any): v is definedNonNullAny => v !== undefined && v !== null

export const definedNonNullAnySchema = z.any().refine((v) => isDefinedNonNullAny(v))

export const TraceSortSchema: z.ZodType<
  "DURATION_ASC" | "DURATION_DESC" | "SPAN_COUNT_DESC" | "START_DESC",
  "DURATION_ASC" | "DURATION_DESC" | "SPAN_COUNT_DESC" | "START_DESC"
> = z.enum(["DURATION_ASC", "DURATION_DESC", "SPAN_COUNT_DESC", "START_DESC"])

export const TestResultStatusSchema: z.ZodType<
  "BROKEN" | "FAILED" | "PASSED" | "SKIPPED" | "UNKNOWN",
  "BROKEN" | "FAILED" | "PASSED" | "SKIPPED" | "UNKNOWN"
> = z.enum(["BROKEN", "FAILED", "PASSED", "SKIPPED", "UNKNOWN"])

export const TestFlakyStateSchema: z.ZodType<
  "BROKEN" | "FIXED" | "FLAKY" | "HEALTHY",
  "BROKEN" | "FIXED" | "FLAKY" | "HEALTHY"
> = z.enum(["BROKEN", "FIXED", "FLAKY", "HEALTHY"])

export const TestExplorerSortSchema: z.ZodType<"LAST_SEEN" | "NAME", "LAST_SEEN" | "NAME"> = z.enum(
  ["LAST_SEEN", "NAME"]
)

export const TestRollupSchema: z.ZodType<
  "BROKEN" | "FAILED" | "FLAKY_PASS" | "PASSED" | "SKIPPED" | "UNKNOWN",
  "BROKEN" | "FAILED" | "FLAKY_PASS" | "PASSED" | "SKIPPED" | "UNKNOWN"
> = z.enum(["BROKEN", "FAILED", "FLAKY_PASS", "PASSED", "SKIPPED", "UNKNOWN"])

export const TestIdentitySourceSchema: z.ZodType<
  "CODE_REFERENCE" | "EXPLICIT" | "NAME_PATH",
  "CODE_REFERENCE" | "EXPLICIT" | "NAME_PATH"
> = z.enum(["CODE_REFERENCE", "EXPLICIT", "NAME_PATH"])

export const SignalKindSchema: z.ZodType<
  "ERRORS" | "LOGS" | "METRIC_POINTS" | "SPANS" | "TRACES",
  "ERRORS" | "LOGS" | "METRIC_POINTS" | "SPANS" | "TRACES"
> = z.enum(["ERRORS", "LOGS", "METRIC_POINTS", "SPANS", "TRACES"])

export const IssueSortSchema: z.ZodType<
  "EVENTS" | "FIRST_SEEN" | "LAST_SEEN" | "TREND",
  "EVENTS" | "FIRST_SEEN" | "LAST_SEEN" | "TREND"
> = z.enum(["EVENTS", "FIRST_SEEN", "LAST_SEEN", "TREND"])

export const TestConfigurationFilterInputSchema: z.ZodObject<
  Properties<TestConfigurationFilterInput>
> = z.object({
  key: z.string(),
  value: z.string(),
})

export const AttributeFilterInputSchema: z.ZodObject<Properties<AttributeFilterInput>> = z.object({
  key: z.string(),
  op: z.string(),
  value: z.string(),
})

export const AlertRuleInputSchema: z.ZodObject<Properties<AlertRuleInput>> = z.object({
  attributeFilters: z.string().nullable(),
  comparator: z.string(),
  consecutiveBreachesRequired: z.number().nullable(),
  consecutiveHealthyRequired: z.number().nullable(),
  destinationIds: z.array(z.string()).nullable(),
  enabled: z.boolean().nullable(),
  excludeServices: z.array(z.string()).nullable(),
  groupBy: z.string().nullable(),
  id: z.string().nullable(),
  metricAggregation: z.string().nullable(),
  metricName: z.string().nullable(),
  minimumSampleCount: z.number().nullable(),
  name: z.string(),
  noDataBehavior: z.string().nullable(),
  renotifyIntervalMinutes: z.number().nullable(),
  services: z.array(z.string()).nullable(),
  severity: z.string(),
  signalType: z.string(),
  threshold: z.number(),
  thresholdUpper: z.number().nullable(),
  windowMinutes: z.number(),
})

export const GraphqlContractStaticProbeQuerySchema: z.ZodType<GraphqlContractStaticProbeQuery> =
  z.object({
    health: z.string(),
    version: z.string(),
    otlpGrpcPort: z.number(),
    otlpHttpPort: z.number(),
    overview: z.object({
      spanCount: z.string(),
      errorRate: z.number(),
      activeServices: z.number(),
    }),
    issue: z
      .object({
        fingerprint: z.string(),
        title: z.string(),
        eventCount: z.number(),
      })
      .nullable(),
    metricNames: z.array(z.string()),
    signalCountSeries: z.array(
      z.object({
        tsNanos: z.string(),
        value: z.number(),
      })
    ),
  })
